### PR TITLE
Election Rework

### PR DESCRIPTION
**Pull request by zumbak04**
Changelog:
- No more "culturism and faithism" in the Horde and the Alliance. Horde's and Alliance's electors don't care about religion and culture of candidate.
- Reworked AI voting logic. For example, Light followers now prefer to vote for humble, chaste, patient characters while Loa worshipers vote for proud, ambitious and brave ones.
- Culture and religion now have greater influence on appearance of characters with certain traits like humble, chaste and patient if it's Light follower or honest and brave if it's orc.
- Reworked elections of "Undead Horde", "Demonic Legion" and "Black Pact". Now elector's votes aren't equal and depend on martial, intrigue, combat skills, real size. Current ruler's and powerful vassals' words are worth more.
- Death God worshipers prefer to elect the one who holds Frostmourne.

### CODE REVIEW

**Comment by geffe1** [comment]
ck2_222
ck2_220

**Comment by geffe1** [comment]
Also noticed that the "A new faction" event didn't happen, thus leaving a lot of old alliance as tributaries to you. I have tried it twice on this branch and once in the old, in the old it fired.
ck2_217

Also Artha's description is the only new one of the ones I wrote that appeared on the "suggested" characters that is interesting to play as. Unsure if that is meant to be the case or not.

**Comment by zumbak04** [comment]
> Also noticed that the "A new faction" event didn't happen, thus leaving a lot of old alliance as tributaries to you. I have tried it twice on this branch and once in the old, in the old it fired.

> Also Artha's description is the only new one of the ones I wrote that appeared on the "suggested" characters that is interesting to play as. Unsure if that is meant to be the case or not.

Update the branch, so now it should be fixed.

**Comment by geffe1** [comment]
>Update the branch, so now it should be fixed.

fixed.

**Comment by MemeWizard** [comment]
>orc mercenary don't like tribal monarchy orc because tribalists are uncivilized barbarians.

ok

<details>

image

</details>

>Reworked AI voting logic. For example, Light followers now prefer to vote for humble, chaste, patient characters while Loa worshipers vote for proud, ambitious and brave ones.

>Now content troll think that content Grommash is spineless.

ok

<details>

image
image

</details>

>human thinks that demon is too old to rule the burning legion

ok

<details>

image

</details>

>this guy don't like candidate because he is wicked man

ok

<details>

image
image
image

</details>

**Comment by zumbak04** [comment]
> orc mercenary don't like tribal monarchy orc because tribalists are uncivilized barbarians.

Vanilla thing. Bands and holy orders hate tribals.

> Now content troll think that content Grommash is spineless.

"Spineless" is nagitive opinion about humble characters.

> this guy don't like candidate because he is wicked man

Wicked man is one who has low piety.

**Comment by MemeWizard** [comment]
>Vanilla thing. Bands and holy orders hate tribals.

And how about change it for the Horde?

>Wicked man is one who has low piety.

And Legion piety called impiety.
So, wicked man is the one who has low impiety? Untitled

**Comment by zumbak04** [comment]
> And how about change it for the Horde?

Mmmkay, can do it.

> And Legion piety called impiety.
> So, wicked man is the one who has low impiety? Untitled

Can change localization to "He is a holy/unholy man".

**Comment by MemeWizard** [comment]
>Can change localization to "He is a holy/unholy man".

Still will be weird, imo.

>Or just "He has low/high [Piety Name]".

Will be better, i think.

**Comment by zumbak04** [comment]
> > Vanilla thing. Bands and holy orders hate tribals.
> 
> And how about change it for the Horde?

Implemented!

> human thinks that demon is too old to rule the burning legion

Fixed!

> > Or just "He has low/high [Piety Name]".
> 
> Will be better, i think.

Implemented!

**Comment by MemeWizard** [comment]
>undeads can die soon

<details>

image

</details>

**Comment by zumbak04** [comment]
> undeads can die soon

Removed this part of localization!

**Comment by MemeWizard** [comment]
Why monarchies called a clan?

<details>

image
image
image
image
image
image

</details>

**Comment by zumbak04** [comment]
> Why monarchies called a clan?

Fixed!

**Pull request merged**
