### PR TITLE
Dynasty CoAs sorting

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Made sure dynasties use CoAs that suit them (no more murloc emblems on human CoAs). The CoAs are the same, I just sorted them.
- Old Ways, Vindicatory, Sargerite, Shath'gral, Voidfarer religions, and Elementalist group use their dynastic CoAs as realm flags.

## Script changelog (ignore if you can't read CK2 script):
- Categorized guild_pattern.
- Moved silly CoAs to silly_pattern.

# How to test:
Take a look at dynastic CoAs of different religions, tell me your opinion (they suit rulers or not).

### CODE REVIEW

**Comment by zumbak04** [comment]
@cal0497 
> I've had a look and they all look the same to me to be honest.

The CoAs are the same. I haven't added anything new, I just sorted them.

> As I have seen several Holy Light rulers with somewhat menacing CoAs which I do not think they would actually use.

Which ones?

**Comment by cal0497** [comment]
I tested this by scrolling through in ruler designer under the Holy Light religion.

Okay so from my testing I have found that all CoAs up to around CoA 80 are of decent resolution. But they are the vanilla ones. All the others bar a few are pretty low res and look terrible. As they did in vanilla. 

I think the modded ones start from 159? and are all good up until around 168 when the resolution makes them look pretty bad. Also why would Holy Light Rulers have animals such as a cobra on their CoA?

180-184 CoA are too big and have been squished which doesn't look great. They are also pretty irrelevant for Holy Light rulers.

190 looks like the eye of Sauron. So pretty malevolent.
189 looks pretty low res but could be a nice CoA once that's sorted.  
191-195 Are all some form of monster CoA excluding 194 which is a lion in a similar fashion to the SW flag. Why would anyone else use this?
197 is randomly higher res than the other CoA and looks much better for it.
199 is a three taloned claw. I can't see many Holy Light rulers using that.
203-208 are all slightly squashed and would look 10x better in a higher res.
226 looks like frostmourne. Don't know why anyone who isn't scourge would put that on their flag.
227 looks squashed
233 looks stretched
239 looks stretched
241 is also an eye and looks evil.
242 looks squashed
244 Looks like a pylon with lightning around it. Also looks squashed. Would look better if appropriately sized.
246 is stretched
250 I think it is a fist holding a lightning bolt. All well and good however it is too low res to make it out.
253 Is a volcano I think. It is pretty small and you have the rest of the CoA to use.
256-263 are all low res but appropriate.
264 I think is a chess piece. A Queen? Looks squashed and fat.
266 is low res
269 and 270 are both low res and would be much nicer.
274 is a hoof I think. I don't think any Holy Light rulers have cloven hooves
276 277 are both squashed slightly
278 and 279 are both low res. Would look better in a higher res.
287 looks malevolent

**Comment by MemeWizard** [comment]
@zumbak04, about that "low-quality" thing. I can convert them to vector if you find the original images for me.

> As I have seen several Holy Light rulers with somewhat menacing CoAs which I do not think they would actually use.

Why not? Coat of arms can be menacing sometimes.

<details>
<summary>Click to expand</summary>

image
image
image
image

</details>

**Comment by cal0497** [comment]
@MemeWizard 

None of those are menacing. The majority of them consist of animals or creatures which would be considered evil. Warcraft is a high fantasy universe where there may be a demon under your bed. I find it highly unlikely that any true holy light ruler would put such a creature on their flag.

**Comment by MemeWizard** [comment]
> The majority of them consist of animals or creatures which would be considered evil.

Snakes and Boars were considered evil, yet CoAs with Snakes and Boars exist.

> Warcraft is a high fantasy universe where there may be a demon under your bed. I find it highly unlikely that any true holy light ruler would put such a creature on their flag.

Personally, I couldn't find any CoAs that looks evil enough to not pick them when checked in RD.

**Comment by zumbak04** [comment]
@cal0497 

> Also why would Holy Light Rulers have animals such as a cobra on their CoA?

I don't think snakes are considered evil on Azeroth since there's no Christian background.

**Comment by zumbak04** [comment]
> @zumbak04, about that "low-quality" thing. I can convert them to vector if you find the original images for me.

@MemeWizard originals from WoW?

**Comment by cal0497** [comment]
@MemeWizard I dont think boars were considered evil. Dangerous and beastly yes. But not evil. Also there are very few snake CoA relstively from my knowledge anyway.

What I meant to say was unlike in our universe Warcraft has very real demons. And it is unlikely anyone would put a symbol of a demon or evil force that has been ravaging the world.

**Comment by MemeWizard** [comment]
> originals from WoW?

I have no idea where these from.

> I dont think boars were considered evil.

Oh, are you sure?

***Very*** rough translation of "Wild boar, Devil beast" from "Michel Pastoureau - The symbolic history of the European Middle Ages."

<details>
<summary>Click to expand</summary>

> Almost without departing from the discourse of ancient texts and preserving behind the boar all those epithets awarded to him by Latin authors (acer, ferox, fulmineus, saevus, violentus, etc.), the Church Fathers turned the animal that Roman hunters, Celtic druids and German warriors so admired, in an unclean and terrifying beast, trampling the Good, securing for him the image of a sinner, rebelling against God. Augustine, commenting on Psalm 80, which refers to the wild boar. A few decades later, Isidore of Seville draws attention to the fact that boar got its name because of its ferocity: “A boar (arer) is called that because of its ferocity (a feritate), replacing the letter p with f” (“Arer a feritate vocatus , ablata f littera et subrogata p dicitur ”). Finally, in the 9th century, Rabanus Moor finally assigned infernal symbolism to the boar, placing it in the very center of the devilish bestiary. Some of his statements will be repeated word for word in the Latin bestiary of the 11th – 12th centuries, and then in the great encyclopedias of the 13th century.

> In the same era, similar thoughts about the diabolical origin of the ferocity of a boar are found in sermons, exempla, treatises on vices and bestiaries. The bravery of a boar, sung by Roman poets, turned into blind and destructive cruelty. His nocturnal lifestyle, dark suit, eyes and fangs, as if to sparking sparks, all make him see a beast that emerged from the very abyss of hell to torment people and rebel against God. The wild boar is ugly, it sprinkles with saliva, smells bad, makes a fuss, it has a striped bristle, standing on end on its back, and “from its mouth 5 horns grow ”; everything is clear: the boar is the embodiment of Satan.

> At the end of the Middle Ages, the negative image of a wild boar even thickens, since it begins to be attributed to the vices that until then had been endowed only with a domestic pig: dishonesty, gluttony, intemperance, lust, laziness. In the representations and perceptions of people of the early Middle Ages, these animals did not mix; starting from the XIV century, this happens with some frequency, if not often. This confirms how the death of King Philip the Beautiful at the end of 1314 was perceived. He died in an accident during a hunt in the Compiegne forest in a collision with a boar. Two or three centuries earlier, such a death would have been perceived as heroic, moreover, truly royal. But at the beginning of the XIV century, everything was already different. This death, although it was the wild boar that became its culprit, reminds contemporaries of the strange death of Prince Philip, son of Louis VI the Fat, about two hundred years before: in October 1131 on the street of Paris an ordinary "porcus diabolicus", as Suger writes, threw himself under the feet of the horse on which the young prince was riding, as a result of which the latter fell from the horse and died, and the Capetian dynasty was covered with indelible disgrace. According to the custom of the first Capetian kings, which was supposed to ensure the continuity of the dynasty, Prince Philippe was crowned king of France during his father’s life. An ordinary homeless pig caused the death of rex junior jam coronatus, and this death throughout the Christian world was perceived as extremely shameful. Nothing outwardly similar to the death of Philip the Beautiful in November 1314. Nevertheless, in the chronicles, libels and pamphlets, the idea that the French monarchy was again the victim of a pig and that the disgraced king paid in this way for all his meannesses and betrayals is emphasized every now and then. The unshakable once symbolic border between the domestic pig and the wild pig has ceased to be insurmountable.

> Indeed, starting from the middle of the 13th century, in theological sums of vices, in exempla collections, and also in literary or iconographic bestiaries, which deals with the seven deadly sins, the boar seems to have gathered all the sins and vices that used to be distributed between domestic and wild pigs: violentia (cruelty), furor (rage), cruor (wildness), ira (wrath), superbia (pride), obstinatio (stubbornness), rapacitas (greed), impietas (wickedness) - on the one hand ; sorditia (unscrupulousness), foeditas (ugliness), libido (lust), intemperantia (intemperance), gula (gluttony), pigritia (laziness) - on the other. When at the end of the Middle Ages a mechanically composed system of seven sins was formed, opposed to seven virtues, the boar was the only one of all animals, who is honored to become a symbol of six of the seven deadly sins: superbia (pride), luxuria (lust), ira (wrath), gula (gluttony), invidia (envy) and acedia (sloth)! He is not attributed only to avaritia (greed). In German miniatures and tapestries of the 15th century, where under the guise of a spear fight or tournament, a confrontation of vices and virtues is depicted, the wild boar appears as the mount, crest or heraldic emblem of any of the six personified mortal sins mentioned above. In the camp of the adversaries of Christ, the boar is the undisputed leader.

> However, the same infernal nature of the boar several decades earlier sought to emphasize and Henry de Ferrers in his "Books about King Modus and Queen Ratio", when he listed ten moral qualities of the boar, equating them with the ten "commandments of the Antichrist". They again refer to five or six deadly sins: pride, anger, lust, idleness, gluttony and, possibly, envy. And the physical appearance of the animal with all its features reminds of hell: black hair, prickly bristles reared on the back, an unbearable smell, terrifying roar, aggressiveness during the rutting season, sudden outbursts of rage, fangs that tear apart everything. The descriptions of the boar in the 14th century did not differ so much from the descriptions of the Roman authors, just all the qualities that in pagan Antiquity were admirable now make you see an infernal creature in the boar.

</details>

> What I meant to say was unlike in our universe Warcraft has very real demons. And it is unlikely anyone would put a symbol of a demon or evil force that has been ravaging the world.

The only "demon or evil force that has been ravaging the world" coas I could find are these, but they are not available for holy light rulers anyway. 

<details>
<summary>Click to expand</summary>

image

</details>

I can't agree that any other "menacing" coas you mentioned in previous reviews are evil, they are just simple animals, weapons and symbols, that are not evil "as is".

**Comment by cal0497** [comment]
@MemeWizard Yes I am sure.

Boar were hunted and by giving them the name Devil beast is more than likely going to drive from the sheer strength and ferocity ancient boar would possess. Most wild boar around now are a hybrid breed and even then they are considered dangerous. But not evil.

But say what you want it's just feedback at the end of the day and there is no need to get defensive about my opinion. 

Holy light rulers should be bastions of the light and paragon of virtue. As most of them are. It's a minority in warcraft who aren't  and their flags should reflect it. But they dont. That was the overriding point. And the rest of them are so low quality that they dont look good.

**Comment by zumbak04** [comment]
> From what i could gather watching them in the world map aswell as in the ruler designer i dont find a problem on how the CoAs look at the moment. Sadly i cant compare much to what is ingame (WoW) or lore, what i could see on the chronicles book...not having much but the well known CoA of lordaeron or the symbols of the different orcish clans, so there isnt much on where to look for CoAs for the WoW universe, maybe this might also be a good thing as you can be more imaginative on what to use (like the runes added for the Fel religions)

@Nelpok so you're fine and don't see anything weird?
> Holy light rulers should be bastions of the light and paragon of virtue. As most of them are. It's a minority in warcraft who aren't and their flags should reflect it. But they dont. That was the overriding point.

@cal0497 I moved the CoAs you wanted except the "Frostmourne" (because it doesn't look like Frostmourne to me especially with this shield outline).
> And the rest of them are so low quality that they dont look good.

Let's leave the quality issue for another PR. The CoAs are already in the game and I just sorted them.

**Comment by BronzeBaron** [comment]
* Old Ways
* Vindicatory 
* Sargerite 
* Shath'gral
* Voidfarer religionsand Elementalist group use their dynastic CoAs as realm flags.

**Comment by zumbak04** [comment]
> Specifically noticed Dar'khan Drathir's, but several High Elven portraits remind me of a mixture of Furbolg style banners and Shath'gral/Void/Death God in their style. It doesn't really strike me as High Elven-esque banners, otherwise, everything else I checked out seems okay. Will add more to this review later.

Dar'khan Drathir's religion is exactly Death God, he should have that banner.

**Comment by zumbak04** [comment]
@Kaisustrin 

> Windrunner banner changes from the latest bookmark compared to the other two. There's more living members of the Windrunners who aren't Forsaken cult; is it based off lordship titles, since Sylvanas has land and is considered patriarch, therefore her religion changes the crest though there's more living Windrunners?

Fixed in 34a6909bdb7ec6268975a98933b04a8aea7e8210.

> Proudmoore's crest is blank?

Fixed in 79def0f43c77d33a90652e04a43ff595df72e7ee.

> Both Malfurion and Tyrande's crests feel uninspiring, but that's more of a personal feeling then anything else.

Mmmkay, I added a CoA of Tyrande, but not Malf in 6085bb10da5aa123af6fa28e0673a7437036bad4.

**Pull request merged**
