### PR TITLE
9th Bug Crusade

### PR DESCRIPTION
**Pull request by zumbak04**
Changelog:

- Infertile characters like undead, demons no longer can be cuckolded.
- Fixed issue where you could get notification of characters becoming undead/demon after religious conversion.
- Fixed issue where Rotmiera had no portrait.
- Fixed issue where satyrs could spawn debutante being only-male race.
- Fixed issue where Annihilan summoned by "The Voice in Your Head" event chain, couldn't raid because he was too old.
- Fixed issue where Warchief of the Horde, created via Ruler Designer, couldn't get "The Invasion from Draenor" event.
- Fixed issue where Alexstrasza and other non-mammals could get Troubled or Difficult Pregnancy.
- Fixed issue where the game didn't give librams to spawned paladins after the creation of the Silver Hand.
- Fixed issue where nomads couldn't get max taxes and troops from Magocracy, Tribal Monarchy and other new governments.
- Fixed issue where nomads couldn't revoke Undead Horde, Demonic Legion, Black Pact governments without penalties like other non-evil governments.
- Fixed issue where HFP.16006 event could fire for indestructible artifact.
- Now Uther has "Light's Hope" province in the RoC bookmark.
- Fixed issue where event that turns character into Demon could fire twice.
- Leader of the Shadow Council no longer can appoint shadow councilors in its own council.

Non-bug changelog:

- Adapted pregnancy and birth events for mammal races like humans, quilboars, gnolls etc.
- Lowered Intrigue requirements to be necromancers, warlocks, shadow priests. Lowered Learning requirement to be paladins, death knights.

Note for testers:
Test it a lot: try to play both mammals and non-mammals.

### CODE REVIEW

**Comment by MemeWizard** [comment]
>Adapted pregnancy and birth events for mammal races like humans, quilboars, gnolls etc.

I didn't see any pregnancy and birth events for mammals

**Comment by zumbak04** [comment]
> I didn't see any pregnancy and birth events for mammals

Fixed! Was caused by broken brackets.

**Comment by geffe1** [comment]
> * Infertile characters like undead, demons no longer can be cuckolded.
Appears to be fixed, still needs a bit more testing.
ck2_26
> * Fixed issue where you could get notification of characters becoming undead/demon after religious conversion.
Fixed!
> * Fixed issue where Rotmiera had no portrait.
Fixed if this creature is meant to be a filthy Satyr.
> * Fixed issue where satyrs could spawn debutante being only-male race.
Fixed.. yet not fixed, removing a feature is not fixing it! :inserts pepevanas here::insert whip here:

The rest I need to continue to look at.

**Comment by geffe1** [comment]
>Fixed issue where Warchief of the Horde, created via Ruler Designer, couldn't get "The Invasion from Draenor" event.

Fixed? I assume? I didn't get to go far as.. people wanted me dead 👎 
ck2_29

**Comment by geffe1** [comment]
>Fixed issue where Alexstrasza and other non-mammals could get Troubled or Difficult Pregnancy.

Appears to work, seen the green and red dragon mate.. it was nasty, but they did raise children without any pregnancy problems.
>Fixed issue where the game didn't give librams to spawned paladins after the creation of the Silver Hand.

Saw like 3 paladins get their librams however they were not the ones in the bottom text. So I assume it works like intended?
>Fixed issue where nomads couldn't get max taxes and troops from Magocracy, Tribal Monarchy and other new governments.

Fixed, however it is pretty confusing which belongs to which at times.. should probably clarify that somewhere.
>Fixed issue where nomads couldn't revoke Undead Horde, Demonic Legion, Black Pact governments without penalties like other non-evil governments.

Fixed.
>Now Uther has "Light's Hope" province in the RoC bookmark.

Fixed

Still need to test:

>Leader of the Shadow Council no longer can appoint shadow councilors in its own council.
>Fixed issue where HFP.16006 event could fire for indestructible artifact.
>Fixed issue where event that turns character into Demon could fire twice.

**Comment by zumbak04** [comment]
> Saw like 3 paladins get their librams however they were not the ones in the bottom text. So I assume it works like intended?

There must be 5 paladins! I tested it a few times, there were 5. These ones were candidats, I hid them.

> Fixed, however it is pretty confusing which belongs to which at times.. should probably clarify that somewhere.

What exactly?

**Comment by geffe1** [comment]
>What exactly
The new governments and which laws to pass to make them give you more levies or money.

**Comment by zumbak04** [comment]
> The new governments and which laws to pass to make them give you more levies or money.

All mod governments except evil ones. It's not a law, it's a nomad feature.
image

**Comment by geffe1** [comment]
> > The new governments and which laws to pass to make them give you more levies or money.
> 
> All mod governments except evil ones. It's not a law, it's a nomad feature.
> image


Works like it is meant to, as the opinion of me is below 0, and he is still forced to hand me the troops as if we were at a 100. 
ck2_32

**Pull request merged**
