### PR TITLE
Religion/Culture Change Issues

### PR DESCRIPTION
**Pull request by zumbak04**
Feature Changelog:
- Dark (Fel, Necromancy, Void religion groups) and Secular (Arcane, Draconic, Elementalist, Nerubian, Secular religion groups and Voidfarer religion) religions no longer send missionaries via RIP.4100 and ZE.5000 events.
- AI can pick Heritage and Faith focuses now. BUT! Rulers that prefer multiculturalism or multireligiosity (like the Horde or the Alliance) are not going to pick it.

Bug Changelog:
- Fixed a few ways to bypass religion/culture change restrcitions:
  - Fixed issue where you could bypass religion/culture change restrictions by taking religion/culture of child's Guardian. Example: sending your naga child to Human Light Priest.
  - Fixed issue where physician-missionary, spawned in RIP.4100, could convert nonconvertible characters (like Evil Shath'yar N'raqi) at your court.
  - Fixed issue where you could convert nonconvertible characters at your court by using Convert to Local Culture, Convert to Attacker's Religion, Falsely Confess Faith (like convert your N'raqi child via Convert to Local Culture).
  - Children, born in prison, take mother's religion and culture instead of warden's like it happens in vanilla.

### CODE REVIEW

**Comment by geffe1** [comment]
ck2_391
Got this to happen after a marriage, will retry it again and comment with an update if it is still the case if I redownload the branch.

**Comment by zumbak04** [comment]
> Got this to happen after a marriage, will retry it again and comment with an update if it is still the case if I redownload the branch.

Fixed!

**Comment by geffe1** [comment]
>Fixed issue where you could bypass religion/culture change restrictions by taking religion/culture of child's Guardian. Example: sending your naga child to Human Light Priest.

Can't see it happening due to heritage and faith being blocked for nagas.

>Fixed issue where physician-missionary, spawned in RIP.4100, could convert nonconvertible characters (like Evil Shath'yar N'raqi) at your court.

Fixed.

**Comment by zumbak04** [comment]
> > Fixed issue where you could bypass religion/culture change restrictions by taking religion/culture of child's Guardian. Example: sending your naga child to Human Light Priest.
> 
> Can't see it happening due to heritage and faith being blocked for nagas.

@geffe1 WAD... but you can try to avoid it... by... starting as human, getting a child, taking Heritage focus and then converting him to Shath'yar. Even in this case, the child shoudn't be able to take religion and culture of Guardian.

**Comment by zumbak04** [comment]
> When (and if) I can convert this child (has kind trait), it's no longer will be able to convert, because it's already too old.

> Also, if you convert to something non-evil, you will not be able to convert your children

Children with Affectionate trait or deviant parents can change religion from Death God, Legion and Shath'yar.

> Also, tooltip is weird.
Can't do anything with it. Two different scripted triggers: the first for religion chance, the second for culture change.

> Also, if I can't convert them, why I must keep them at my court until they grown up to purge them?

Allow child execution?

**Comment by MemeWizard** [comment]
> Can't do anything with it.

Changed!

> Allow child execution?

At least banishing.
Players have zero reasons to keep character at their court that will be killed right after it will become adult.

**Comment by zumbak04** [comment]
> > Allow child execution?
> 
> At least banishing.
> Players have zero reasons to keep character at their court that will be killed right after it become adult.

Oh, wait, you said banishing... I heard beheading... well, it's too late to change anything! :3

**Pull request merged**
