### PR TITLE
Grummle portraits

### PR DESCRIPTION
**Pull request by sejtalk**
## Changelog:
- Added Grummle placeholder portraits for both genders.

## Developer changelog:
- Clothes and the rest will be added at a later date.

### CODE REVIEW

**Comment by zumbak04** [comment]
Their children look bigger than adults.

<details>
<summary>Click to expand</summary>

image
image

</details>

**Comment by zumbak04** [comment]
The PR doesn't mention how to see these portraits.

**Comment by zumbak04** [comment]
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/wiki/Portrait-Guide#cutting-screenshots

**Comment by Kyraga** [comment]
They do look like children for me either way.

**Comment by zumbak04** [comment]
> Children portraits look like children for me either way, both the old version and a new one.

Agree. Can't even spot out the difference without a side-by-side comparison. My problem is that adults look too small to be adults.

**Pull request merged**
