### PR TITLE
3rd Flags

### PR DESCRIPTION
**Pull request by Gnomebuster**
### Changelog:
<details>
<summary>A lot of flags</summary>

- gfx/flags/c_bambala.tga
image

- gfx/flags/c_draktharon.tga
image

- gfx/flags/c_mount_kajaro.tga
image

- gfx/flags/c_scarab_wall.tga
image

- gfx/flags/d_astranaar.tga
image

- gfx/flags/d_badland.tga
image

- gfx/flags/d_cleftlands.tga
image

- gfx/flags/d_darkshore.tga
image

- gfx/flags/d_dreadmist.tga
image

- gfx/flags/d_dryslope.tga
image

- gfx/flags/d_dun_algaz.tga
image

- gfx/flags/d_eastern_arathi.tga
image

- gfx/flags/d_frosthold.tga
image

- gfx/flags/d_glaive_isle.tga
image

- gfx/flags/d_grim_batol.tga
image

- gfx/flags/d_high_northeron.tga
image

- gfx/flags/d_indule.tga
image

- gfx/flags/d_irontree.tga
image

- gfx/flags/d_jaedenar.tga
image

- gfx/flags/d_kharanos.tga
image

- gfx/flags/d_krensen.tga
image

- gfx/flags/d_lethlor.tga
image

- gfx/flags/d_ludei.tga
image

- gfx/flags/d_northfold.tga
image

- gfx/flags/d_raven_hill.tga
image

- gfx/flags/d_raynewood.tga
image

- gfx/flags/d_redrock.tga
image

- gfx/flags/d_scarab_wall.tga
image

- gfx/flags/d_shaibi.tga
image

- gfx/flags/d_shatterspear.tga
image

- gfx/flags/d_stonewrought.tga
image

- gfx/flags/d_sunstrider_isle.tga
image

- gfx/flags/d_talonbranch.tga
image

- gfx/flags/d_thunder_bluff.tga
image

- gfx/flags/d_torwatha.tga
image

- gfx/flags/d_tranquillien.tga
image

- gfx/flags/d_west_dun_morogh.tga
image

- gfx/flags/d_zulmamwe.tga
image

- gfx/flags/e_storm_peaks.tga
image

- gfx/flags/k_storm_peaks.tga
image

</details>

### How to Test
You know... just look at flags.

### CODE REVIEW

**Comment by MemeWizard** [comment]
d_thorvald is masterpiece
I really like d_dordanil
Imo, d_red_cloud, d_redhelm and d_west_dun_morogh have too realistic images for flags
Rest are good

**Comment by MemeWizard** [comment]
>Tell whatchu think about flags

I don't like d_badland and d_raven_hill colors. It's warm color emblem on warm color background/cold color emblem on cold color background

Also, try this for references

http://wappenwiki.org/index.php?title=Heraldic_Elements
http://wappenwiki.org/index.php?title=Main_Page

**Comment by MemeWizard** [comment]
d_ludei and d_zulmamwe are too acidic
It's physically painful to look at them

**Comment by MemeWizard** [comment]
d_zulmamwe looks better, but that outline looks weird

**Comment by zumbak04** [comment]
I will divide the review into 2 parts: **_Rework Later_** and **_Needs More Work_**.
**_Rework Later_** means that I would rework these flags later.
**_Needs More Work_** means that I believe there shall be more work before these flags being merged.

## Rework Later
I'm ok with these 3D-like flags now, but I would rework them later.
<details>
<summary>Click to expand</summary>

- gfx/flags/k_storm_peaks.tga
- gfx/flags/e_storm_peaks.tga
- gfx/flags/d_thunder_bluff.tga
- gfx/flags/d_stonewrought.tga
- gfx/flags/d_shaibi.tga
- gfx/flags/d_frosthold.tga
- gfx/flags/d_eastern_arathi.tga

</details>

## Needs More Work
gfx/flags/d_zulmamwe.tga has very sharp edges.

gfx/flags/c_scarab_wall.tga has too small symbol.

These have too weird 3D-like style:

<details>
<summary>Click to expand</summary>

- gfx/flags/d_krensen.tga
- gfx/flags/d_kharanos.tga
- gfx/flags/d_indule.tga
- gfx/flags/d_dryslope.tga

</details>

These flags have acid colors:

<details>
<summary>Click to expand</summary>

- gfx/flags/d_torwatha.tga
- gfx/flags/d_ludei.tga

</details>

These flags not visible on their backgrounds:

<details>
<summary>Click to expand</summary>

- gfx/flags/d_shatterspear.tga
- gfx/flags/d_lethlor.tga
- gfx/flags/d_grim_batol.tga
- gfx/flags/d_dun_algaz.tga
- gfx/flags/d_astranaar.tga

</details>

## P.S.
Other flags are fine. Some of them are really good like gfx/flags/d_queldanas_isle.tga or gfx/flags/d_zolnanji.tga . Thanky, @Gnomebuster!

**Comment by zumbak04** [comment]
Closing since it's inactive.

**Pull request closed without merging**
