### PR TITLE
I am Speed: The Branch

### PR DESCRIPTION
**Pull request by zumbak04**
Changelog:
- Slowed down the army movement speed to the vanilla value.
- Slowed down the navy movement speed by 33%.

Ppl, what's your opinion?
P.S. It's fault of this suggestion https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/574

### CODE REVIEW

**Comment by MemeWizard** [comment]
>Slowed down the army movement speed to the vanilla value.

If you slowed down it to the vanilla value, then you just can delete this value in mod's defines file

**Comment by zumbak04** [comment]
> If you slowed down it to the vanilla value, then you just can delete this value in mod's defines file

I can't, but I won't do it.

**Comment by MemeWizard** [comment]
>I can't, but I won't do it.
:thonk:

**Comment by DukeJeans** [comment]
Stop talking on the PR!

**Comment by zumbak04** [comment]
can*, but now it's even better

**Comment by zumbak04** [comment]
MY PR, MY CASTLE!

**Comment by DukeJeans** [comment]
**:(**

**Comment by zumbak04** [comment]
> **:(**

Is this your official review of the PR?

**Comment by zumbak04** [comment]
> **:(**

Well, he spoke his word.

**Comment by geffe1** [comment]
Hi

**Pull request merged**
