### PR TITLE
3.1.1 Merging

### PR DESCRIPTION
**Pull request by zumbak04**
Changelog:

- 3.1.1 is adapted.
- Now followers of Primitive religion group can "Perform Sky Burial".

Note for testers: Please, guys, test everything from the new patch.

### CODE REVIEW

**Comment by MemeWizard** [comment]
how to get rid of demons 101
<details>

image
image
image


</details>

**Comment by MemeWizard** [comment]
>Now followers of Theradras and Primitive religions can "Perform Sky Burial".

nope
you can't, because HLF.8001 is not adapted

**Comment by geffe1** [comment]
The shadow council events for placing shadow council members into blackhand's court doesn't appear to work like they should, got the event to fire once by killing off 25 or so orcs that got a council position in blackhand's council without me getting the event to fire.

**Comment by zumbak04** [comment]
> you can't, because HLF.8001 is not adapted

Adapted!

**Comment by zumbak04** [comment]
test

**Comment by zumbak04** [comment]
test

**Comment by zumbak04** [comment]
2 test

**Comment by geffe1** [comment]
> > you can't, because HLF.8001 is not adapted
> 
> Adapted!
Pst, this one now works properly!

**Comment by geffe1** [comment]
ck2_69
this good old event kept getting spammed, day after day while raiding the two provinces east of the starting position as the Qiraji of Ahn'Qiraj. Unsure to why exactly as I never got into the city for it to actually happen, and the town is unlooted like you see in the picture above.

**Comment by zumbak04** [comment]
> this good old event kept getting spammed, day after day while raiding the two provinces east of the starting position as the Qiraji of Ahn'Qiraj. Unsure to why exactly as I never got into the city for it to actually happen, and the town is unlooted like you see in the picture above.

I believe it's Paradox's fault and our siege was bugged somehow, but I added modifier that blocks twice firing of this event. Should help.

**Comment by MemeWizard** [comment]
Is there any point in "historical great works" gamerule with just only one available option?

<details>

image

</details>

**Comment by zumbak04** [comment]
> Is there any point in "historical great works" gamerule with just only one available option?

Yep, it's hardcoded rule and I don't want to break something.

**Pull request merged**
