### PR TITLE
Take Vows - Endorsed Bloodlines Fix

### LINKED ISSUE #839: [LOCALIZATION] | Kaldorei papacy
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
masterbranch
**Please explain your issue in as much detail as possible:**
Kaldorei papacy- I thought they had their High Priestess.
**Upload screenshots of the problem localization:**
ck2_386

### PR DESCRIPTION
**Pull request by DJScias**
Hello there,

Changed the line to state `High Priest` instead of `Papacy`. Reason I've used that term and not "High Priestess" is due to the other term used more in other places for the religion as seen here:
image
image

The outcome of these changes are as follows:
image

This PR should fix #839.

### CODE REVIEW

**Comment by zumbak04** [comment]
I would do a dynamic localization `[Root.RelHead.GetTitle]` (references to title of religious head of ROOT) instead of High Priest. Should work.

**Comment by DJScias** [comment]
I'll look into that.

**Comment by DJScias** [comment]
Updated this PR to work with `[Root.RelHead.GetTitle]`.

Outcome:
image

**Comment by zumbak04** [comment]
@DJScias merge?

**Comment by DJScias** [comment]
Should be good to merge.

**Pull request merged**
