### PR TITLE
2nd Religious Icon Rework

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Reworked icons of Goldrinn, Helya, Death God religions by Cryyc. Other icons are resized.

## Developer changelog:
- Purged Druidic religion since it was used by one realm only: the frost nymphs.

# How to test:
Enter the game, check the characters of the said religions.

### CODE REVIEW

**Comment by zumbak04** [comment]
> Please fix Nightwell, Belore, Arcane, Earth Mother, Tidemother, Throsic religious icons. I’ll check all of the religious icons in one batch as soon as the fix is rolled out.

Fixed Earth Mother, Tidemother, Throsic in f30c03c55cfef700bb4422d1e36ed040656f0072.
Belore and Arcane are fine.
Nightwell is removed some time ago. Do you see the Changed files here?
<details>
<summary>Click to expand</summary>

image

</details>
If you do, right-click the Changed files, Discard all changes.

**Comment by Kyraga** [comment]
> Do you see the Changed files here?

No, no changed files there.

<details>
  <summary>Github desktop</summary>

Github desktop
</details>

Are you saying that I shouldn't see Nightwell religion in the game at all?

**Comment by zumbak04** [comment]
> Are you saying that I shouldn't see Nightwell religion in the game at all?

Yep. If you use submods, disabled them.
<details>
<summary>Click to expand</summary>

image

</details>

**Comment by Kyraga** [comment]
> If you use submods

Yep, Warcraft: GoA Models mod messed things up. I disabled it.

**Comment by zumbak04** [comment]
I checked the icons you both agree on. They all are the same size: 40x40 max as it should be. They just have different shapes. Like the buddhist wheel looks bigger than the catholic cross.

**Comment by zumbak04** [comment]
> I am not saying the icon size is incorrect. I am saying that the non-resized version of these particular icons looks prettier and more detailed, in my opinion, than the resized version.

Less detail is an unavoidable consequence of resizing, so I don’t understand what you mean here. Making them prettier isn't a goal of this PR.

**Pull request merged**
