### PR TITLE
Dwarven Portraits

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added Frostborn, Wildhammer, Bronzebeard and Dark Iron dwarven portraits together with the undead and fel versions.

# How to test:
`event WCPOD.5013` to become an undead.
`event WCFEL.9950` to spam Fel Corruption and become a demon.

After this, try to invite courtiers, check if they have racial traits.

### CODE REVIEW

**Review by Deuce20201 — CHANGES_REQUESTED** [review]
First of all, I love the new dwarven portraits. 

I also love the new demon portrait you guys put in. However it's the same portrait for Frostborn, Wildhammer, Bronzebeard, etc. Is there no way to differentiate them? 

However what I do not particularly like is the undead portrait for the dwarves, whether they be frostborn or any other kind. Just a purple haze around the portrait but no truly distinct difference. 

Sorry if this came off as unnecessarily critical.

**Comment by zumbak04** [comment]
Thanks for review!

> I also love the new demon portrait you guys put in. However it's the same portrait for Frostborn, Wildhammer, Bronzebeard, etc. Is there no way to differentiate them?

There's, but it barely worth it. Maybe only for the firstborn due to their unique skin colour.

> However what I do not particularly like is the undead portrait for the dwarves, whether they be frostborn or any other kind. Just a purple haze around the portrait but no truly distinct difference.

Hmm? Undead dwarves have red, blue or yellow eyes and pale skin.
<details>
<summary>Click to expand</summary>

image

</details>

**Review by Malicos — CHANGES_REQUESTED** [review]
Undead dwarves don't work, neither do fel portraits, dwarves turn into generic demons.

EDIT: for some reason it wasn't pulled when I got the branch for the first time

**Comment by zumbak04** [comment]
> EDIT2: I would make separate fel and undead variants for all dwarves, so they retain their outfits - currently Wildhammer and Dark Iron outfits change into Bronzebeard ones when they turn undead/fel.

Changed in 6e249a1199d333508f2a293d62b9cc8b07a53570 and a210b8195d44c77172e2f34a79624576e95da55e.

**Review by Malicos — APPROVED** [review]
looks good

**Review by Deuce20201 — APPROVED** [review]
Very well done. 

Everything seems to work for me.

**Pull request merged**
