### PR TITLE
Culture Switch Limitations

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added limitations of switching to some cultures (affect both culture switch decisions and childhood events):
  - To switch to Aqir culture group, you must be Qiraji or Nerubian.
  - To switch to Demonic and Satyr culture group, you must have Demon trait or follow Sargerite religion.
  - To switch to Nazja and Shath'yar culture group, you must have Void Being trait or follow Shath'yar religion.
  - To switch to Undead culture group, you must have Undead trait or follow Death God religion.

## How to test:
I would recommend to try these things:
- Start as Azshara (I mean location, not character) murlocs in 603, **Swear Filty** to the nagas and...
  - Right click on your portrait, try to convert to liege culture.
  - Right click on liege portrait, try to convert to liege culture.
  - Take naga's land, move capital there, try to convert to local culture by right-clicking on your portrait.
  - Find young children of your dynasty (if you play these murlocs, there are 2 your grandchildren), pick **Heritage** focus, invite naga to your courth, assign the naga as guardian of your children... and wait. They shall not accept Nazja culture if they're not of Shath'yar religion.

### CODE REVIEW

**Comment by zumbak04** [comment]
@Ultearov do you test with all DLCs enabled? Especially Conclave?

**Comment by MemeWizard** [comment]
> do you test with all DLCs enabled? Especially Conclave?

There is no child focuses if player don't have conclave

**Comment by Ultearov** [comment]
> @Ultearov do you test with all DLCs enabled? Especially Conclave?

All except Jade Dragon.

**Comment by zumbak04** [comment]
> Tested for conversion to Nazja from Murloc in Azshara, everything worked out well until one girl became of nazja culture without Being of the Shath'yar religion or being a Void Being. To do so, I gave her a Nazja Guardian, and gave her heritage focus. Note: My first Granddaughter, under the same conditions became of the Shath'yar religion before switching to Nazja.
> 
> Most Likely fixeable around line 4066, within the can_switch_culture_to_prev_character_trigger method.
> 
> Here under is attached a picture of said granddaughter.

I tested Heritage focus and it WAD. Children with Shath'yar converted to Nazja, others not.
<details>
<summary>Children that started with Nerglish religion</summary>

image
image
image
image

</details>

<details>
<summary>Children that started with Shath'yar religions</summary>

image
image

</details>

So, I doubt it's Heritage focus fault... especially because Heritage can't change culture without changing religion.
Soo, it looks like some random event and I need to know ID to find it.

**Comment by zumbak04** [comment]
@Ultearov wait, I have one idea. Could it be that your grandchild is secret Shath'yar?

**Comment by Ultearov** [comment]
> @Ultearov wait, I have one idea. Could it be that your grandchild is secret Shath'yar?

After checking through multiple methods, it does not seem so.

**Pull request merged**
