### PR TITLE
World Trees

### PR DESCRIPTION
**Pull request by zumbak04**
Changelog:
- Added a decision to plant a world tree if you're a great druid of the Druidic religions.
- Added a decision to corrupt a world tree if you're Shath'yar.
- Added a decision and an event after a siege to burn a world tree if you're not Druidic.
- Night elves now are immortal until Nordrassil is destroyed.

Note for Devs:
There're `plant_world_tree_effect`, `corrupt_world_tree_effect`, `burn_world_tree_effect` effects. If you want to add more commands that fire when these things happen with a tree do it here

### CODE REVIEW

**Comment by zumbak04** [comment]
@SlagartheCruel , @DukeJeans , need your reviews of localization here. Hit this link, only 00_zuwc_united_localisation.csv needs proofreading:
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/245/files?file-filters%5B%5D=.csv#diff-177f28deabd40e49753f6ba47a622790

**Comment by MemeWizard** [comment]
Huh?
Should the first option be available?

<details>
<summary>Click to expand</summary>

ck2_1

</details>

**Comment by zumbak04** [comment]
> Huh?
> Should the first option be available?

Forgot to mention that I fixed it.

**Comment by MemeWizard** [comment]
"Can be destroyed" is very misleading tooltip

**Comment by zumbak04** [comment]
> "Can be destroyed" is very misleading tooltip

The tooltip was cahnged to "Unique building does NOT block it".

**Comment by MemeWizard** [comment]
So, druids can't do anything with nightmarish tree?
<details>
<summary>Click to expand</summary>

ck2_9

</details>

**Comment by zumbak04** [comment]
> So, druids can't do anything with nightmarish tree?

Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/245/commits/e664d5a95a68e9234c41e1dfc8caafcd0358d3dc!

**Comment by MemeWizard** [comment]
- there is no flavor event when you plant a tree

- moral authority is given to the current religion of the character, not the religion that the character was when he planted a tree.

<details>
<summary>Click to expand</summary>

ck2_15

</details>

- You can plant a tree when you play as a non-independent ruler with an non-druidic liege, but why will it then be inactive when it grows up?

<details>
<summary>Click to expand</summary>

ck2_16

</details>

**Comment by zumbak04** [comment]
Oopsie, forgot to answer.

> * there is no flavor event when you plant a tree

Added.

> * moral authority is given to the current religion of the character, not the religion that the character was when he planted a tree.

Now if your religion isn't druidic, it stops world tree event chain and gives piety and gold back.

> * You can plant a tree when you play as a non-independent ruler with an non-druidic liege, but why will it then be inactive when it grows up?

I believe this condition is kinda confusing, because you can always give this temple to your vassal and the tree will become active, but ok. Now it checks condition of liege.

**Comment by MemeWizard** [comment]
>Now if your religion isn't druidic, it stops world tree event chain and gives piety and gold back.

What if the player changed religion at the time when the tree had already grown, but before clicking on event?

<details>
<summary>Click to expand</summary>

ck2_1
ck2_2

</details>

**Comment by MemeWizard** [comment]
> * there is no flavor event when you plant a tree

>Added

>Now if your religion isn't druidic, it stops world tree event chain and gives piety and gold back.


If your character has a world tree in the province, he dies, and the heir belongs to another religion, then there is no flavor event either.

**Comment by zumbak04** [comment]
> > * there is no flavor event when you plant a tree
> 
> > Added
> 
> > Now if your religion isn't druidic, it stops world tree event chain and gives piety and gold back.
> 
> If your character has a world tree in the province, he dies, and the heir belongs to another religion, then at that moment when the tree should have grown, it will simply disappear from the province, there is no flavor event.

**Comment by zumbak04** [comment]
> What if player changed religion at the time when the tree had already grown, but before clicking on event?

Fixed!

> If your character has a world tree in the province, he dies, and the heir belongs to another religion, then at that moment when the tree should have grown, it will simply disappear from the province, there is no flavor event.

Ok, now it shows that the tree couldn't germinate.

**Comment by MemeWizard** [comment]
Growing trees cannot be burned.
Also, tooltip is wrong, it's actually gives 2 holding slots.
<details>
<summary>Click to expand</summary>

ck2_4
ck2_5

</details>

Also, I really don't like that you get 100% of the resources back if you fail to grow a tree
Don't punish player for mistakes is a bad game design for *C A S U A L S*

<details>
<summary>Click to expand</summary>



</details>

**Comment by zumbak04** [comment]
> Growing trees cannot be burned.

Now you can't plant world tree if temple is looted.

> Also, tooltip is wrong, it's actually gives 2 holding slots.

"New World Tree" event no longer show added holding slots to other players.

> Also, I really don't like that you get 100% of the resources back if you fail to grow a tree
> Don't punish player for mistakes is a bad game design for _C A S U A L S_

Now it returns only 50% of spent gold and piety.

**Pull request merged**
