### PR TITLE
AI building Old Gods Issue

### PR DESCRIPTION
**Pull request by sejtalk**
## Developer changelog:
- The AI can no longer ignore `potential` block and build an Old God wonder upgrade without waking the Old God.
- Replaced `cthun_offmap_decisions_enabled_trigger` and `nzoth_offmap_decisions_enabled_trigger` by modifiers to prevent possible bugs.

# How to test:
Let the game run on observer mode for 30 years and check if the AI is building/had built old god wonder upgrade(you can make sure they did by checking their religion, country history and old god status).

### CODE REVIEW

**Review by Myrran — APPROVED** [review]
The AI wasn't building/didn't build an Old God wonder upgrade in my observer run.

Although I did experince some strange behaviour while testing other branches before. Specifically, N'zoth was killed a little too soon. I noticed some kind of revolt going on in Shrine of Storms province before that happened. Well, hope this fix will solve the problem.

**Comment by sejtalk** [comment]
> The ai built the c'thun wonder, despite him only being partially free. Not sure why, but this is definitely a bug.

Partially free means first tier upgrade is spawned with event. it gets replaced with better version when fully free

**Comment by sejtalk** [comment]
> > The ai built the c'thun wonder, despite him only being partially free. Not sure why, but this is definitely a bug.
> 
> Partially free means first tier upgrade is spawned with event. it gets replaced with better version when fully free

Unless the ai follows wrong old god/ is wrong religion it should be fine.

**Review by zumbak04 — APPROVED** [review]
LGTM!

**Pull request merged**
