### PR TITLE
29th Bug Crusade

### LINKED ISSUE #1349: WoL.520 can lead to Lover's Pox
**Your mod version is:**
9ef9cfa1807725de559bb64bfa91756a08d23d53

**What expansions do you have installed?**
All

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
Undead can get `WoL.40` (tries to add Lover's Pox) via `WoL.520`.

**Steps to reproduce the issue:**
Not needed.

**Upload an attachment below: .zip of your save, or screenshots:**

### LINKED ISSUE #1361: Keep Old Gods powers on religion change
**Your mod version is:**
47a8a31a7c1ee412ec3a6bb41d5444d67bc089fa

**What expansions do you have installed?**
All

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
You keep Old Gods' offmap powers on religion change.

**Steps to reproduce the issue:**
Get offmap power modifiers, switch religion (easy to do if you change the religion change game rule).

**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

image
image

</details>

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Fixed #1361 issue where you kept the Old Gods' powers from the **Request Power from Old God** after a switch to a non-Old Gods' religion.
**_How to test:_** being an Old Gods' follower, pick the main Old God, get power from him via the offmap interface and convert to other religion.
- Aman'Thul is now the Highfather instead of the Highmother.
**_How to test:_** View Aman'Thul's character sheet by going up through the family tree from Ulduar titan keeper characters (i.e. Thorim, Loken, etc.).

## Developer changelog:
- Fixed an issue where there were depopulated Quel'thalas and Dalaran in the 605 bookmark if you didn't have the Reaper's Due DLC.
- Fixed an issue where Gilneas got Darius' revolt in the bookmark selecting menu if you picked the 605 bookmark and then switched to the early ones.
- Fixed an issue where you could genocide the province with ongoing genocide.
- Fixed an issue where the Horn of Cenarius didn't exist in the 605 bookmark.

## Script changelog (ignore if you can't read CK2 script):
- Replaced vanilla `impregnate = yes`, `impregnate = 0` by `unknown_impregnate_this_effect` to prevent possible bugs and create debug messages in the log.
- Replaced vanilla `impregnate_cuckoo = yes` by `unknown_impregnate_cuckoo_this_effect` to prevent possible bugs and create debug messages in the log.
- Fixed #1349 issue where the undead characters could get `WoL.40`.
- Added `if` block in `WoL.98` that hides chances of impregnation if character can't be pregnant.
- Added `set_cannot_marry_or_find_spouse_effect` to replace big chunks of script.
- Fixed `3140` (Theramore province) not being a part of `island_kalimdor`.
- Fixed `d_dun_niffelem`, `d_tunkalo`, `d_ulduar` not being parts of `island_northrend` and `world_northrend_storm_peaks`.
- Fixed `e_pantheon` where `HIGHFATHER_FEM_TITLE` was only available title.

# How to test:
Just a few console tips to save your time:
- `religion old_gods_worship` to convert to the Old Gods' religion.
- `religion holy_light` to convert to the Holy Light (not-Old Gods' religion)
- `add_offmap_currency offmap_cthun 10000` to get 10000 C'thun's currency.
- `add_offmap_currency offmap_nzoth 10000` to get 10000 N'zoth's currency.
- `add_offmap_currency offmap_yoggsaron 10000` to get 10000 Yogg-Saron's currency.

### CODE REVIEW

**Comment by KoiKarp** [comment]
if you use the latest start date, and then go back to an earlier one Darius Crowley becomes independent instantly and a few counties beyond Hothillis, before you start the game it appears as Gilnean revolt as not at war with Gilneas.

**Comment by KoiKarp** [comment]
suggestion: you should lose armies and generals requested from old gods if you convert, atm you keep them after coverting.

**Comment by zumbak04** [comment]
> if you use the latest start date, and then go back to an earlier one Darius Crowley becomes independent instantly and a few counties beyond Hothillis, before you start the game it appears as Gilnean revolt as not at war with Gilneas.
Fixed in 52b973b2aa58627f4732b5b98e8d341397bc87a1.

> suggestion: you should lose armies and generals requested from old gods if you convert, atm you keep them after coverting.
Reported here https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/1430.

**Comment by KoiKarp** [comment]
Clicking the "Purge Population" decision does the normal genocide, however you can click it again but it doesn't do anything.

**Comment by zumbak04** [comment]
> Clicking the "Purge Population" decision does the normal genocide, however you can click it again but it doesn't do anything.

@KoiKarp ooof, good call, big bug, fixed in 3c3fb2111b7981b8b9c4eab583602d8b0a516558.

**Comment by KoiKarp** [comment]
if Illidan wins the war against Arthas, he usurps a bunch of holdings in Sylvanas' realm.

**Comment by zumbak04** [comment]
> if Illidan wins the war against Arthas, he usurps a bunch of holdings in Sylvanas' realm.

Good catch again, fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/1423/commits/35c9d01200de72c601c2de4823cf8d80a0c9eb2f.

**Pull request merged**
