### PR TITLE
19th Small Improvments

### LINKED ISSUE #1162: Gamerule to disable faction unification
**Describe your suggestion in full detail below:**
Hey Devs, I love the mod and (Mostly) everything about it.
Something that really annoys me is that I barely play the later start dates because of the forced unification of the Alliance, which turns about 50-90% (depending on the run.) of the Eastern Kingdoms into a dark blue blob. 
So something I hope can be added is a gamerule to disable faction unification, if possible.
Thanks for reading :)

### LINKED ISSUE #1228: Replace Plot Restrictions with Plot Defence
**Describe your suggestion in full detail below:**
Replace plot restrictions of killing the Scourge/Legion/Black Empire leaders with plot defense.

### LINKED ISSUE #1273: Allow to Abduct Undead
**Describe your suggestion in full detail below:**
You should be able to abduct weak undead, satyrs, naga. Maybe it's a good idea to add personal combat skill condition instead.

### LINKED ISSUE #1290: Cultures without unique retinue
**Describe your suggestion in full detail below:**

Add unique retinue for forsaken

### LINKED ISSUE #1296: Change "Claim Capital City" Decision
**Describe your suggestion in full detail below:**

I suggest changing it effect to "character get capital of its primary title".
Currently, characters can usurp capital of non-primary titles and that can be weird sometimes.
For example, in my game, my character's liege with Lordaeron primary title created Dalaran Kingdom and usurped Dalaran that belonged to my vassal,  although liege already has Lordaeron as capital.

### LINKED ISSUE #1298: Make librams stackable
**Describe your suggestion in full detail below:**

Delete `stacking = no` from generic librams, because right now:

1. Your char can't have more than 1 libram of the same type in inventory
2. If your char get second copy from "write libram" decision, it gets nothing instead and just waste 500 piety

### LINKED ISSUE #1303: Rework accepting new dynasty members
**Describe your suggestion in full detail below:**
Rework `WCCOU.200`, an event that allows infertile characters to accept new dynasty members, into a decision where you pay something (gold, prestige, piety etc.).

It would be nice to allow vampires and worgens to share their curse with new dynasty members.

### LINKED ISSUE #1342: Siege Engines might be a little bit too powerful.
**Describe your suggestion in full detail below:**
Title. Fully upgraded these siege engines have 0.41/0.01/0.01. Just for comparison Cav has 0.02/0.11/0.08. Siege engines have more value in just the ranged phase, than Cav over the entire duration of the fight. Which I guess makes sense, given that some siege engines are literal tanks. But if you approach late game and have a retinue size of over 30k+ and just stack that one siege retinue for an army of 5k Tanks they just decimate everything the Ai throws at them. With ease at that (including armies 4x the size). So maybe that needs a little bit of fine tuning.

### LINKED ISSUE #1397: Purge WCUND.200
**Describe your suggestion in full detail below:**
Purge `WCUND.200` since it's not used

### LINKED ISSUE #1458: [SUGGESTION] | Wildhammer ruler correction
**Describe your suggestion in full detail below:**
Apparently, we didn't really display the wildhammer rulers correctly. In the mod, as it is right now, Falstad rules since the opening of the Dark Portal. According to wowwiki, Falstad's brother [Kurdran ](https://wowwiki.fandom.com/wiki/Kurdran_Wildhammer) was thane at the time of the opening of the Dark Portal until he went to Draenor with the Alliance Expedition. Then, Falstad took over, In the first startdate, it should definitely be his brother, who rules the clan.

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added a game rule, "Political Faction Unification": you can start with the factions where new members join as vassals from the very begging or where new members always join as tributaries.
- You can plot to kill the Scourge (if the Lich King isn't trapped)/Legion/Black Empire leaders, but they have plot defense.
- The Legion/Black Empire leaders got Combat Rating and attribute bonuses.
- You're allowed to abduct undead, demons, and naga via the society abduction decision.
- Added Dark Rangers retinue for Forsaken culture.
- Added Undead Swarm retinue for Scourge culture.
- The librams created via a paladin's decision, Write Libram, are stackable (you can have a few librams of the same type in your inventory).
- The death knights of any level can use Forge Runeblade decision.
- The paladins of any level can use Write Libram decision.
- Added a decision to adopt the right-clicked character if you can't reproduce other ways.
- Made siege machines 38% weaker.
- Kurdran is a ruler of the Wildhammer clan in the 583 startdate.

## Script changelog (ignore if you can't read CK2 script):
- Reworked claim_capital_city, got rid of scripted triggers. It usurps a county of your primary title now.
- Added can_adopt_characters_trigger.
- Merged WCRAC.300 and WCCOU.200.
- WCRAC.310 is no longer on action event. It fires in WCCOU.200.
- Purged WCUND.200 since it's not used.

# How to test:
Just a few tips:
- `culture forsaken` to embrace Forsaken culture.
- `culture scourge` to embrace Scourge culture.
- `add_trait class_paladin_10` to become a paladin.
- `add_trait class_death_knight_10` to become a death knight.
- `add_trait infertile` to make your character unable to reproduce.

Closes #1162, closes #1228, closes #1273, closes #1290, closes #1296, closes #1298, closes #1303, closes #1397, closes #1342, closes #1458.

### CODE REVIEW

**Comment by zumbak04** [comment]
> * There is an issue with this request : I randomly got this problem with every characters on every start date. Not on the same event though, sometimes it's for the "Invasion of Draenor", sometimes at others events... Even with big characters such as Blackhand, the Lich King...

Good catch, fixed in 8c7e95c2f6b58429306a5e5ac2a2520800b3dc77.

**Comment by zumbak04** [comment]
> One point of concern: why is undead swarm composed of aerial infantry? Granted, I'm not entirely sure if it is meant to be composed of gargoyles or something similar, but the name undead swarm seems to imply to me that it is composed of a bunch of mindless zombies. Everything else worked as expected.

@LordSilvermane renamed the retinue gargoyles in b67a772df53ce8cc453b457e2f16fe1d38a15a13.

**Comment by zumbak04** [comment]
@Kaisustrin ooof, you got the wrong PR.

**Comment by zumbak04** [comment]
> Sounds like fun although there is a risk that human players will abuse such mechanic.

I'll think about it more and will try to come up with idea tomorrow.

**Comment by zumbak04** [comment]
@Kyraga allowed adopting claimants in ff02678c8d7fabc7959156e19ed3a0e839ab7bec. Want to hear your opinion.

**Comment by zumbak04** [comment]
> @zumbak04 I don’t like it. It feels unnatural. Me being able to adopt a character from another dynasty just doesn’t seem right no matter if he has claims or not. I’d prefer if only lowborns were adoptable by the living.

Lowborns are a bad idea because even characters invited by the decisions aren't lowborn.

> As for the undead. It might be fun if they were able to adopt imprisoned living characters using “turn undead” decision on them. In this case the undead can be allowed to adopt characters that have dynasty or claims or is an heir.

You use turn undead and then adopt, yes. Plus, what about demons?

**Comment by Kyraga** [comment]
> Lowborns are a bad idea because even characters invited by the decisions aren't lowborn.
Small dynasties then.
 
> You use turn undead and then adopt, yes. Plus, what about demons?
Demons being able to adopt imprisoned characters sounds good. First the imprisoned character is corrupted by fel magic and then adopted.

**Comment by zumbak04** [comment]
> Demons being able to adopt imprisoned characters sounds good. First the imprisoned character is corrupted by fel magic and then adopted.

@Kyraga What about races that can't have children like harpies. I think there should be a universal approach: if you can't get dynastic claims via childbirth, you should be able to adopt claimants.

**Comment by zumbak04** [comment]
> @zumbak04 The universal approach is this:
> If you can't get dynastic claims via childbirth you should be able to adopt lowborn or members of small dynasties (exact size is up to you). I don’t like the idea of allowing members of big dynasties being adopted because it breaks immersion in a game and the roleplaying element.

Don't think it's a good idea. Harpies can't adopt claimants, demons can though they're immortal and it's already a big bonus.

> Undead/demons/void creatures (if lore allows it) get a bonus of being able to adopt imprisoned members of big dynasties after turning them undead/fel corrupting/void corrupting.

There are 3 reasons why I think it's a bad idea.
- Turning undead is easier than other ways. Thus it will be unbalanced.
- If you're a warrior demon that follows non-Legion religion, you can't fel corrupt. If you follow Legion religion, you can fel corrupt, but claims don't make much sense since you have free CBs.
- If you're a demon, but let's say you follow the Holy Light, making other demons doesn't make much sense lore-wise.

Aight, I think I'll limit everyone to small dynasties than since don't think more buffs for the undead, demons, and void beings are good ideas.

**Pull request merged**
