### PR TITLE
Military Overhaul: the Units

### PR DESCRIPTION
**Pull request by zumbak04**
Secret changelog:
Buildings:
- Used relocalized vanilla buildings instead of mod ones to make it easier to balance and fix conversion problems.
- Buffed fort buildings.

Troops:
- Infantry is average of Light Infantry and Heavy Infantry. Cavalry is average of Light Cavalry and Knights.
- Balanced cost and strength of special units and normal troops.
- Made Large Infantry, Aerial Units, Large Cavalry, War Machines, Siege Machines stronger.
- Made sure special troops based on pikemen and light_cavalry get bonuses together with base type.
- Based war_machines on pikemen.
- Rebalanced event troops in scripted effects, events and decisions (1 vanilla pikemen = 1 mod heavy infantry, 1 vanilla heavy infantry = 1 mod heavy infantry, 2 vanilla light infantry = 1 mod heavy infantry).
- Adapted spawn_unit in raise_host_of_the_wilds decision.

Retinues:
- Balanced nomad retinues.
- Balanced tribal retinues.
- Balanced modifiers of other retinues. Every unit in retinue get 40% bonus in total, so we may say it's more or less balanced.

Other:
- Original effect of Strategic Exclaves (Great Wall wonder upgrade) is back. It gives max level of walls to all baronies in province.
- Disabled WCDAC.9990 event. It upgraded tribals and built Evil buildings in baronies when province became Evil (Death God, Legion, Shath'yar religions).
- Made technologies uneven.

### CODE REVIEW

**Comment by MemeWizard** [comment]
Is it ok that tribals almost fully upgraded ?

<details>

image

</details>

No tooltip about available buildings from techs.
<details>

image

</details>

**Comment by zumbak04** [comment]
> Is it ok that tribals almost fully upgraded ?

4 tribal level = 2 castle level. They're not better then castles.

> No tooltip about available buildings from techs.

Added unlocked building lists back.

**Comment by MemeWizard** [comment]
>Added unlocked building lists back.

>Nobuilding I

<details>

image

</details>

**Comment by zumbak04** [comment]
> > Nobuilding I

Fixed!

**Comment by MemeWizard** [comment]
ca_eye_of_eternity building have old "casters" special units
tp_nordrassil building have old "ancients" special units

**Comment by MemeWizard** [comment]
After models deletion, Lordaeron and Dalaran capitals was shifted to the left

<details>

image

</details>

**Comment by zumbak04** [comment]
> ca_eye_of_eternity building have old "casters" special units
> tp_nordrassil building have old "ancients" special units

Fixed!

> After models deletion, Lordaeron and Dalaran capitals was shifted to the left

Fixed!

**Comment by MemeWizard** [comment]
How about move fully commented buildings files to `Guardians of Azeroth\coder_resources\_unused\common\buildings`?

>Buffed fort buildings.

I don't mind it, but are you sure about numbers?

<details>

Безымянный2

</details>

Trade district don't have numeration

<details>

image

</details>

How it should looks like:

<details>

image

</details>

Temple have the same problem

<details>

image

</details>

Also archives

<details>

image

</details>

How it should looks like:

<details>

image

</details>

>Made technologies uneven.

It's rather more annoying that tech are partiality (91%) filled.
How about ~50% fill?

<details>

image

</details>

**Comment by zumbak04** [comment]
> How about move fully commented buildings files to `Guardians of Azeroth\coder_resources\_unused\common\buildings`?

Done!

> > Buffed fort buildings.
> 
> I don't mind it, but are you sure about numbers?

Nerfed percent bonus, but gave more default troops.

> Trade district don't have numeration

> Temple have the same problem

> Also archives

Added!

**Comment by MemeWizard** [comment]
Can you also change names of 4-6 lvl temples from "Great [NAME]" to just "[NAME]"?

<details>

Безымянный

</details>

**Comment by zumbak04** [comment]
> Can you also change names of 4-6 lvl temples from "Great [NAME]" to just "[NAME]"?

Mmmkay... **SAD**

**Pull request merged**
