### PR TITLE
Chogall final step

### PR DESCRIPTION
**Pull request by sejtalk**
## Changelog:
- Cho'gall's journey will now reach his destination in either Ahn'Qiraj or Ulduar and result in weakening chains of an Old God.
- Nerfed amount of troops spawned when freeing an Old God.

## Developer changelog:
- Don't merge before #845

### CODE REVIEW

**Comment by zumbak04** [comment]
Looks like it should be based on the Old God Content instead of the master.
<details>
<summary>Click to expand</summary>

image

</details>

**Comment by zumbak04** [comment]
Wait, what is a point of checking it if #845 isn't finished?

**Comment by sejtalk** [comment]
Cause i didnt fix all the bugs in #845 yet

**Review by zumbak04 — APPROVED** [review]
LGTM!

**Review by Myrran — APPROVED** [review]
Works fine for me.

**Pull request merged**
