### PR TITLE
Merchant Republics

### PR DESCRIPTION
**Pull request by zumbak04**
Changelog:
- Merchant republics are back.
- The Trade Coalition and Stratholme start as merchant republics.
- Now merchant republics hold elections every 12 years.

### CODE REVIEW

**Comment by MemeWizard** [comment]
No loc
<details>
<summary>Click to expand</summary>



</details>

**Comment by geffe1** [comment]
What I have found so far:
ck2_2
You can not build  a tradepost in the capital of Gilneas, which I think should be possible- same goes for the route through the rivers in Twilight Highlands. If that is possible to change somehow?

ck2_5
The other banking families starts with a lot more money than you do, thus you won't get any of the good spots to build a trading post on, I feel they should get their money dragged down or yours up a bit to compensate so that you have a chance to build a good trading post in one of the bigger cities.

**Comment by MemeWizard** [comment]
>The other banking families starts with a lot more money than you do, thus you won't get any of the good spots to build a trading post on, I feel they should get their money dragged down or yours up a bit to compensate so that you have a chance to build a good trading post in one of the bigger cities.

Vanilla thing

<details>
<summary>Click to expand</summary>

image

</details>

**Comment by zumbak04** [comment]
> You can not build a tradepost in the capital of Gilneas, which I think should be possible- same goes for the route through the rivers in Twilight Highlands. If that is possible to change somehow?

You can't build trade posts on rivers.

**Comment by zumbak04** [comment]
> No loc

Fixed!

**Comment by MemeWizard** [comment]
After election your heir banish your old ruler
<details>
<summary>Click to expand</summary>




</details>

**Comment by Sielentus** [comment]
PR

**Comment by MemeWizard** [comment]
There no events about elections, you just lose your main title without any explanations

**Comment by zumbak04** [comment]
> When the Ruler's Brother dies in Stratholme(Merchant Republic), his child is your heir in succession time period, he won't get respect doe to being a child. This is fatal if he is 3 and the succession time period is only 3 years away

Kids can't be elected, it's vanilla thing.

> that next problem is ( i dont know if it is a bug or intended, i think personally the first) when the Ruler loose the succession, then is game over

It's reproducible? If it's, I need to know steps.

**Comment by Sielentus** [comment]
> It's reproducible? If it's, I need to know steps.

yes it is.  support your successor and loose the election. but  this time i got this message :
ck2_1

**Comment by zumbak04** [comment]
> After election your heir banish your old ruler

Fixed!

> that next problem is ( i dont know if it is a bug or intended, i think personally the first) when the Ruler loose the succession, then is game over

Fixed? More testing needed.

**Comment by zumbak04** [comment]
> There no events about elections, you just lose your main title without any explanations

Added!

**Comment by Sielentus** [comment]
> Fixed? More testing needed.

it's fixed. I tried to provoke this bug with 5 new games and 3 custom Leader to this crucial point and everything work fine, as it should be

**Comment by geffe1** [comment]
> > There no events about elections, you just lose your main title without any explanations
> 
> Added!

There is indeed, and it works.
It all seems fixed now as well, I am ready to accept this branch into the family.. however, I would prefer if we had a bit more unique events for the republics.
Examples being: a year before you are about to lose or win the election you get special events that change things, example being the respect points getting removed or added. So for a greedy ruler you could get an option to perhaps get extra cash and "votes" but less money for half a year, due to being corrupt. Would make a republic feel a lot more unique.

**Comment by Sielentus** [comment]
Everything works fine in mid and late game, however i found one Problem.
You can't join a secret Society, as  Merchant Republic member (Stratholme), in fact it does not even Show you all 3 even if you have (for exampel) a negative trait:  Cruel
meh 1
this works only, when you had ( in this case) a Shadow Prist training and this show also only one secret Society  
 
meh 2

**Comment by zumbak04** [comment]
> You can't join a secret Society, as Merchant Republic member (Stratholme), in fact it does not even Show you all 3 even if you have (for exampel) a negative trait: Cruel

Allowed them to join the dark cults.

**Comment by zumbak04** [comment]
> There is indeed, and it works. However I think that there should be a sort of warning a year or half a year before.

Added!

> An examples being: a year before you are about to lose or win the election you get special events that change things, example being the respect points getting removed or added. So for a greedy ruler you could get an option to perhaps get extra cash and "votes" but less money for a year, due to being corrupt.

Later™
Don't worry, we can turn CK2 into Vic3 at any time.

**Comment by geffe1** [comment]
ck2_5
It is there, however I'd prefer if it got changed.
Perhaps to: 
"Every 10 years we hold elections within our republic, next year the elections will be held, this year will be the last chance to influence the outcome if you desire to win it.".

**Comment by zumbak04** [comment]
> It is there, however I'd prefer if it got changed.
> Perhaps to:
> "Every 10 years we hold elections within our republic, next year the elections will be held, this year will be the last chance to influence the outcome if you desire to win it.".

Ok, big boss. You won.

**Comment by MemeWizard** [comment]
>Previous doge of your dynasty now transfers money to next doge of your dynasty after republic elections.

But don't transfers artifacts

<details>

ck2_5

</details>

Also, when republic created, patrician houses can spawn with noculture gfx characters

<details>




</details>

**Comment by MemeWizard** [comment]
Also check this spammy event, it's fires every day

[Scourge607_04_25.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3179109/Scourge607_04_25.zip)

<details>

ck2_5

</details>

**Comment by MemeWizard** [comment]
>Now merchant republics hold elections every 10 years.

One of the conditions for changing gender law is to rule 10 years or more.
So, because of elections, you cannot fulfill this condition and change law.

<details>



</details>

Also, you can change your primary title to avoid elections

<details>



</details>

**Comment by zumbak04** [comment]
> But don't transfers artifacts

Now it transfers.

> Also, when republic created, patrician houses can spawn with noculture gfx characters

Fixed! Was vanilla bug, hope Paradox will fix it soon.

> Also check this spammy event, it's fires every day

Fixed? Now patricians can't adopt evil governments.

> One of the conditions for changing gender law is to rule 10 years or more.
> So, because of elections, you cannot fulfill this condition and change law.

Now there're elections every 12 years to give more time for laws changing.

> Also, you can change your primary title to avoid elections

Fixed? I reworked elections, now election timer is attached to doge. Testing needed.

**Comment by geffe1** [comment]
https://gyazo.com/b4a2dcd15015227bdf97f763a933fb74 this means that the event saying you got elections every 10 years is.. wrong.. very wrong. 2 years wrong in fact, just wanted to state that.

**Comment by zumbak04** [comment]
> https://gyazo.com/b4a2dcd15015227bdf97f763a933fb74 this means that the event saying you got elections every 10 years is.. wrong.. very wrong. 2 years wrong in fact, just wanted to state that.

Just remove "decennially" part or replace?

**Comment by geffe1** [comment]
Been testing it again, everything appears to work fine- checked the things that MemeWizard pointed out and it all seems to be doing ok.

**Comment by MemeWizard** [comment]
When you lose elections, barons in your provinces become vassals of doge.

<details>

image
image

</details>

**Comment by zumbak04** [comment]
> When you lose elections, barons in your provinces become vassals of doge.

Fixed!

**Pull request merged**
