### PR TITLE
Issue #901 Fix

### LINKED ISSUE #901: Alliance leader remains alliance leader after abdication
**Mod Version**
136c94f4

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Alliance leader remains alliance leader after abdication

**Steps to reproduce the issue:**
Load save, surrender.

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

image
image
image

</details>

[Lordaeron603_12_12.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3800263/Lordaeron603_12_12.zip)

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Fixed #901 issue where the former Alliance Leader kept the Leader trait after win of the Overthrow Faction.
**_How to test:_** Play as **Alexei Barov** in 603, start a faction to **Overthrow High King Terenas II of Lordaeron**, open the **Decisions** list, click **Demand Abdication**, switch to Terenas II, accept the demand, watch the result.
- Fixed issue where the player Alliance Leader could **Swear Fealty** to any Empire (like the Horde) if the Alliance Leader wasn't Emperor tier. To prevent this, the Alliance Leader always has at least one Empire title.
**_How to test:_** Try to create the Alliance as different titles and tiers (Lordaeron, Stormwind, Kul Tiras). Try to wait till Lordaeron dies in the 603 bookmark.

## Secret Сhangelog:
- Rewrote localization of `WCPLF.60` event.

### CODE REVIEW

**Comment by spacsea** [comment]
What expansions do you have installed?
All

Please explain your issue in as much detail as possible:
Took these steps: How to test: Play as Alexei Barov in 603, start a faction to Overthrow High King Terenas II of Lordaeron, open the Decisions list, click Demand Abdication, switch to Terenas II, accept the demand, watch the result.

The result was high kingdom of Lordaeron passing to Uther with no noticeable issue.
worked

Repeated the test under circumstances of performing the decision "unify the realm" with king Terenas  first making the alliance properly. The result was Alliance title was destroyed and the realm fractured.
debug2

Can easily repeat this by giving yourself tech as Terenas and firing the event from decisions and then switching to the steps listed.

**Comment by MemeWizard** [comment]
There can be 2 first alliance bloodlines if Terenas create alliance in 583 bookmark, no one joins faction, he abdicate, and then new ruler create the Alliance.

<details>
<summary>Click to expand</summary>

image
image
image
image

</details>

> To prevent this, the Alliance Leader always has at least one Empire title.

I don't think it's ok that empire title copies history of the kingdom

<details>
<summary>Click to expand</summary>

image

</details>

So, there now can be 2 alliance leaders?

<details>
<summary>Click to expand</summary>

image
image

</details>

**Comment by zumbak04** [comment]
> There can be 2 first alliance bloodlines if Terenas create alliance in 583 bookmark, no one joins faction, he abdicate, and then new ruler create the Alliance.

Looks like separate bug, could you report it as issue?

**Comment by zumbak04** [comment]
> > To prevent this, the Alliance Leader always has at least one Empire title.
> 
> I don't think it's ok that empire title copies history of the kingdom

> So, there now can be 2 alliance leaders?

These 2 shall be fixed!

**Comment by MemeWizard** [comment]
In "The New Leader of Faction" event localization tells about current ruler title, not about title that ruler has before becoming leader of the alliance and it looks weird.

<details>
<summary>Click to expand</summary>

image

</details>

**Comment by zumbak04** [comment]
> In "The New Leader of Faction" event localization tells about current ruler title, not about title that ruler has before becoming leader of the alliance and it looks weird.

@MemeWizard it's more easy to find him, no? The old title may be lost among the other titles while the event mentions the current primary title.

**Comment by MemeWizard** [comment]
> it's more easy to find him, no? 

No, since you don't need to find him in character/title finder

<details>
<summary>Click to expand</summary>

image

</details>

**Comment by zumbak04** [comment]
> In "The New Leader of Faction" event localization tells about current ruler title, not about title that ruler has before becoming leader of the alliance and it looks weird.

Mmmkay, done.

**Comment by MemeWizard** [comment]
It's still weird, since new part can be interpreted as "Alliance become United", even if it's not.

<details>
<summary>Click to expand</summary>

image
image

</details>

**Comment by zumbak04** [comment]
> It's still weird, since new part can be interpreted as "Alliance become United", even if it's not.

Mmmkay, done.

**Pull request merged**
