### PR TITLE
More holdings

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added more holdings all over the world, so it should be more close to the vanilla.
- Since there are more holdings, event/decision conditions require more Realm Size.

# How to test:
Since there are more holdings, landed rulers should be stronger, so wait for event-spawned forces like the Qiraji, Scourge, Legion, Horde and tell what you think.
Try to play the tribals. They didn't get holdings, so we may consider buffing them.

A few console commands:
- `event WCFEL.1000` to summon the Legion as your character.
- `event WCUND.99` to spawn the Scourge.

### CODE REVIEW

**Comment by zumbak04** [comment]
> I feel like the invading force always end up burning their event troops to siege the new holdings and quickly win their first or second war, but then lose to a coalition like the Alliance because they can't withstand their increased levies.

@Alvieck do you speak about the Horde? Or like everyone?

**Comment by Kyraga** [comment]
I remember that I started experimenting with invasion strength because x1 Legion was rather weak and was annihilated real fast. If I am not mistaken it was annihilated when Legion tried to conquer Alliance (3-rd bookmark). Therefore my opinion is Legion, Scourge and Qiraji x1 invasion strength needs to be buffed.

**Comment by zumbak04** [comment]
> I remember that I started experimenting with invasion strength because x1 Legion was rather weak and was annihilated real fast. If I am not mistaken it was annihilated when Legion tried to conquer Alliance (3-rd bookmark). Therefore my opinion is Legion, Scourge and Qiraji x1 invasion strength needs to be buffed.

Don't agree on the qiraji. They blob big in my games, while they should be stopped around Uldum.

**Comment by zumbak04** [comment]
@Kaisustrin @Kyraga I did [5 testruns](https://docs.google.com/spreadsheets/d/1jZiJ8BwjAJxA9i7WKgmYXDZIWbCW6kzxavIwFXGKhgM/edit?usp=sharing) and I'm fine with results. The Scourge was able to win even without Arthas in 60% of testruns. The Legion and Scourge stayed big powers in about 50% of testruns.

**Comment by Kaisustrin** [comment]
@zumbak04 Doing a bit more testing, from a purely numbers perspective due to the number of allies Terenas calls in to the war/gets offered for help, I'm still seeing Scourge get practically slaughtered in that regard. Considering all other variables though, I'm not sure how important that is, but yeh.

**Comment by zumbak04** [comment]
> @zumbak04 Doing a bit more testing, from a purely numbers perspective due to the number of allies Terenas calls in to the war/gets offered for help, I'm still seeing Scourge get practically slaughtered in that regard. Considering all other variables though, I'm not sure how important that is, but yeh.

> I have to agree with previous comments. The Scourge and Burning Legion were easily defeated by the AI in my games. I definitely think the Scourge need a slight buff. Less sure about the Legion. They put up more of a fight.

@Kaisustrin @LordSilvermane what the bookmark you played?

**Comment by Kaisustrin** [comment]
@zumbak04 For the sake of ease, I was just doing Reign of Chaos bookmark. I tested....six times, yesterday. First try was 2x strength, Scourge defeat. Rest of the tries were 1x since I figured I'd try it base strength and in all scenarios, from a purely numbers perspective, the Scourge lost every large battle I saw but one and only won through situations such as Terenas turning/Calia going Lich Queen(since for some reason its almost always Calia and not Arthas.)
I did observer mode to simply watch the conflicts play out as they would naturally.
Legion seemed to win 1x most of the time unless they made a grave mistake and let Tyrande/Cenarius get their armies together.
But overall, it looked as if Legion's soldiers were stronger then Tyrandes and/or they had better generals and Terenas' mass alliance had stronger soldiers and/or better generals then Scourge, since even in fights the Scourge had the numbers advantage, they lost hard.

**Comment by zumbak04** [comment]
> @zumbak04 I played tribals a bit and they seem fine to me.
> While playing I noticed there are some provinces with tribal governments and barony/city vassals under them. I made a list of such provinces for all 3 bookmarks. You might want to remove temple holdings, that’s up to you.
> 
> [More holdings tribals.xlsx](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/4717208/More.holdings.tribals.xlsx)

@Kyraga very good catches. Fixed in 13d6d5ccf4069ab33bebea3910075589d832b15d. Check the comment, I explained how I picked provinces to change.

**Comment by zumbak04** [comment]
Don't know guys, I gave the Scourge 15% buff and played the game from 583, that's what happened.
<details>
<summary>Click to expand</summary>

image

</details>

**Comment by zumbak04** [comment]
@Kaisustrin @LordSilvermane gave 15% buff to the Scourge and Legion. Did [3 testruns](https://docs.google.com/spreadsheets/d/1jZiJ8BwjAJxA9i7WKgmYXDZIWbCW6kzxavIwFXGKhgM/edit#gid=0&range=B11:G11), my statistics look kinda sad, but combined with yours, I think it's fine.

**Comment by Kyraga** [comment]
> Don't know, guys, I gave the Scourge 15% buff and played the game from 583, that's what happened.

@zumbak04 I don't understand why did you play from 583, then spawn Scourge in 591? Why not play 2-nd bookmark from 603?

**Comment by zumbak04** [comment]
> @zumbak04 I don't understand why did you play from 583, then spawn Scourge in 591? Why not play 2-nd bookmark from 603?

Tested the 603 before where I got pretty high winrate of the Legion and Scourge. I though it's different from the 583 bookmark.

**Comment by Kyraga** [comment]
> Tested the 603 before where I got pretty high winrate of the Legion and Scourge. I though it's different from the 583 bookmark.

@zumbak04 
- I am not sure if it should but Scourge doesn't spawn naturally for me in 603 in 1-st bookmark. And I have "Warcraft: Scourge Spawn" game rule set to "Always"
- event WCUND.99 gives Scourge 64k event spawned while in 2-nd bookmark they start with 16k event-spawned and then get additional event-spawned during the war with Lordaeron.
- event WCFEL.1000 gives 39600 event spawned while in 603 Legion gets 26400 event spawned.
I am playing the build before 15% buff.

**Comment by Kyraga** [comment]
@zumbak04 okay, I see the problem. If I am in observer mode than the Scourge won't spawn. If I am playing a real character it does spawn. 64k troops in 1-st bookmark.

**Comment by Kyraga** [comment]
So, basically the Scourge from 1-st bookmark has more event-spawned troops left when they start the war to conquer Lordaeron than the Scourge from the 2-nd bookmark.

**Comment by Kyraga** [comment]
@zumbak04 
Here are the results of the test runs.

Horde, Scourge and Qiraji are pretty clear.

Legion is somewhat different. Legion lost 8 times out of 10.

They lost once because they didn’t have enough manpower to fight off the aggressor and two times when they failed to conquer Hyjal at the start of the invasion. These are the cases when you can give them extra troops to help tip the scales in their favor.

Other five times Legion lost because Legion AI declared Great War while having lots of accumulated threat. That led to Defensive pacts being formed against Legion. With over 80% threat all defensive pacts of other religious groups band together if you attack one of them. Overall I noticed that invaders (or AI in general) do not take threat/defensive pacts into account when declaring wars. AI doesn’t understand that if they lose the war, it is game over for them. From a player perspective it is not fun when Legion commits suicide by declaring Great War while having high threat. My opinion is this problem needs to be dealt before making any balance adjustments to the Legion.

[More holdings test runs.xlsx](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/4728087/More.holdings.test.runs.xlsx)

**Comment by zumbak04** [comment]
> * event WCFEL.1000 gives 39600 event spawned while in 603 Legion gets 26400 event spawned.
>   I am playing the build before 15% buff.

The Legion receives more troops each summoning iteration.

> So, basically the Scourge from 1-st bookmark has more event-spawned troops left when they start the war to conquer Lordaeron than the Scourge from the 2-nd bookmark.

The Scourge needs more troops in the 1st bookmark to conquer Icecrown and surroundings. The Lich King often loses to the Drakkari (seen it in 1/3 runs after the buff).

> I see. But tribals have an option to pillage conquered holdings, completely destroying them in the process. I used that option when playing tribals to have more empty holdings in a province.

The AI never destroys them because it's more profitable to keep holdings. So if the AI conquered these provinces, he would build a tribal and keep holdings.

> Legion is somewhat different. Legion lost 8 times out of 10.

I'm fine with this since they can return and become stronger.

> Overall I noticed that invaders (or AI in general) do not take threat/defensive pacts into account when declaring wars. AI doesn’t understand that if they lose the war, it is game over for them. From a player perspective it is not fun when Legion commits suicide by declaring Great War while having high threat. My opinion is this problem needs to be dealt with before making any balance adjustments to the Legion.

I believe they take, but there's always a chance. There are [AI behavior modifiers](https://ck2.paradoxwikis.com/Modifiers#List_of_modifiers). Don't think it's a good idea because there are no chances to win the Legion except defensive pacts or other big blob states.

**Comment by zumbak04** [comment]
> Right now the Legion has a self-destruct mechanism and as a player I don't need to do anything - just wait for the Legion to self-destruct. What's the fun in that? It looks unnatural. Increasing invasion strength through game rule won't help - the result will be the same.

There's no self-destruct mechanism, it's just how the AI works in CK2. I'm against changing it. It may affect other realms and make the game less dynamic.

> What about Scourge and Qiraji? There are results for all four factions in the file attached.

The Scourge looks spooky, but I'm fine.

**Comment by Kyraga** [comment]
@zumbak04 will you keep Scourge and Legion 15% buff or revert it back?

**Comment by zumbak04** [comment]
> @zumbak04 will you keep Scourge and Legion 15% buff or revert it back? My tests were made without 15% buff.

Most likely yes, but before the revert, I would like @LordaeronEmbassy @Kaisustrin to test the buff.

**Comment by zumbak04** [comment]
> Reign of Chaos bookmarks. Parameters: Initial conquest of Hyjal and initial conquest of Lordaeron.
> Five runs, normal strength Scourge and Legion.
> Scourge: 0/5 victories. Third war, Scourge looked as if it might win the biggest battle of the war, but then Terenas succumbed to the Plague and turned undead.
> Legion: 5/0 victories. Second war, Legion lost over half its event troops, but pulled through and claimed the Hyjal victory.
> Five runs, 1.5x Scourge.
> 1/5 Scourge victories.
> First war, decisive battle at Lordamere Lake, ended from Terenas succumbing to plague. Though, Scourge lost every major battle before that.
> Second war, Scourge lost almost every major battle again but won the war through holdings capture(I think.)
> Every other war was Scourge losing every major battle but turning Terenas due to plague or just outright losing.

Combined with my and @Kyraga results, it gives the Scourge 30-40% winrate, I'm fine.

**Pull request merged**
