### PR TITLE
Orcish Dynasty Shields

### PR DESCRIPTION
**Pull request by MemeWizard**
#### Changelog:
- Added new orcish dynasty shields

<details>
<summary>Click to expand</summary>

image

</details>

#### How to test:
- Check that they work and don't go beyond dynasty shield

### CODE REVIEW

**Comment by MemeWizard** [comment]
> they could also work well for other races, especially ogres, who iirc do not have any unique shields, and have similar banner designs to the ones depicted here

Well... Shields are tied to religions, so if we want to give it to someone else, we need to add these shields to specific religions. Currently, new shields are used by `orcish_fel` (Fel-tainted) and `orcish_shamanism` (Ancestral) religions, do you have any other religions in mind that could use these shields?

**Comment by LordSilvermane** [comment]
> Well... Shields are tied to religions, so if we want to give it to someone else, we need to add these shields to specific religions. Currently, new shields are used by `orcish_fel` (Fel-tainted) and `orcish_shamanism` (Ancestral) religions, do you have any other religions in mind that could use these shields?

Crap, should've remembered that, thought it was culture for some reason. In that case, guess not. I'd say fetishistic, because most of the designs would fit a few of the races (particularly ogres, magnataurs, and gnolls), but it just wouldn't work for the others (especially tuskarr, gorlocs, harpies, and hozen). Shame.

**Comment by zumbak04** [comment]
> Crap, should've remembered that, thought it was culture for some reason. In that case, guess not. I'd say fetishistic, because most of the designs would definitely fit a few of the races (particularly ogres, magnataurs, and gnolls), but it just wouldn't work for the others (especially tuskarr, gorlocs, harpies, and hozen). Shame.

Don't know. I think they fit Fetishistic except maybe gorlocs. I expect something from "aquatic" from them though gorlocs live near swamps, not seas.

**Comment by zumbak04** [comment]
Could you remove `guild_pattern`? **It breaks aesthetics.**

**Comment by MemeWizard** [comment]
> Could you remove guild_pattern? It breaks aesthetics.

Sure!
*I hope it won't break anything*

**Pull request merged**
