### PR TITLE
Lore character portraits

### PR DESCRIPTION
**Pull request by sejtalk**
Changelog

- Added Tyrande and Night Warrior Tyrande portrait
- Added Malfurion and Malfurion Bear Form portrait
- Added Maiev portrait
- Added Illidan and demon Illidan portraits
- Added Cenarius portrait
- Added Mylune portrait
- Added Medivh and demon Medivh portrait
- Added Genn portraits

### CODE REVIEW

**Comment by MemeWizard** [comment]
Tyrande, Medivh and Genn looking in 1/4 angle, not in 1/2.
Also, Tyrande, Medivh and Genn are too far away from portrait ring, in comparing with other portraits.
Medivh and Illidan don't have unique demon portraits.

<details>
<summary>Click to expand</summary>

ck2_5
ck2_6

</details>

Idk how to see NW Tyrande portrait in-game.

**Comment by sejtalk** [comment]
> Tyrande, Medivh and Genn looking in 1/4 angle, not in 1/2.
> Also, Tyrande, Medivh and Genn are too far away from portrait ring, in comparing with other portraits.
> Medivh and Illidan don't have unique demon portraits.
> 
> Click to expand
> ck2_5
> ck2_6
> 
> Idk how to see NW Tyrande portrait in-game.

Fixed demon portraits. I'll make changes to portraits for next update.

**Comment by MemeWizard** [comment]
>Fixed demon portraits.

Ok.
>Tyrande, Medivh and Genn looking in 1/4 angle, not in 1/2.
Also, Tyrande, Medivh and Genn are too far away from portrait ring, in comparing with other portraits.

Same problems with demon Illidan&demon Medivh

**Comment by zumbak04** [comment]
Good

**Pull request merged**
