### PR TITLE
10th Small Improvements

### PR DESCRIPTION
**Pull request by zumbak04**
Changelog:

- Now you can get Alliance Founder bloodline if there's ongoing horde invasion.
- Gave more prestige and piety to Blackhand.
- "Join the Scourge/Legion/Black Empire" decisions now require evil government type.
- Non-evil characters can always join factions against evil liege and vice versa.
- Horde' and Alliance' vassals now prefer to revolt against liege if there's no either elections or council power.
- Theramore is connected to mainland. Plus, now Theramore get more lands after founding.
- AI joins faction even if leader isn't in diplomatic range, but has good opinion.
- Stop Invader CB can be used against evil empires or big evil realms like qiraji.
- Negative fertility of some race traits is replaced by "Infertile" trait. Such long-lived races and immortal characters get it when they have too many children. Non-long-lived races get it when they reach andropause/menopause age.
- "Heal Wounds" decision now removes pending infection.
- After "Exodus of the Horde", "Founding of Theramore" event chains, landless non-heir character from your dynasty gets abandoned titles if you have one. Otherwise, your liege gets these titles.
- Now there's 33% chance that spawned via "Stop Invader" CB rulers will have evil religion like Legion, Shath'yar or Death God.
- Now adventures become independent instead of becoming your vassals.
- Menethil Harbor is now dwarven territory.
- Increased success chance of "Bad Voodoo", "Drive Mad" and "Mind Control" decisions.
- Ok, now the Kaldorei Empire and its vassals REALLY prefer to stay it de-jure borders.
- Rulers with Alliance culture and religion now prefer not to attack Dalaran and Gnomeregan in their de-jure borders.
- Now new rulers of Gnomeregan and Ironforge can instantly propose alliance to each other via event chain.
- "Hunt Apostates" job action is available for Evil rulers.
- Now it's possible to send Court Chaplain with "Proselytize" job action in Evil province only if you has the same culture as province.
- Character and province culture conversion is restricted. Characters and provinces with Aqir, Demonic, Naga, Satyr, Shath'yar, Undead cultures can change culture only if their religion isn't Death God, Legion and Shath'yar.
- Random level up now takes more time if you reach high levels (7-9 levels). Also, 7 and 8 level of magical class no longer give long life.
- "Burn Evil Being" and "Burn Evil Beings" decisions can be now used to get reason to execute your landed vassals. AI just takes their lands via these decisions.
- Only small and medium humanoids can be rogues.
- You no longer can use your Chancellor to improve diplomatic relations with Death God, Legion and Shath'yar rulers.
- Sometimes the game spawns groups of sea invaders like kvaldir, naga and murlocs to settle on your coast. "Adventurers" vanilla game rule affects their spawning. (Note for testers: tell me if this happens too often).
- Now player has more chances to get the Ashbringer.
- Added the Aluneth artifact.
- Emperors, kings and independent rulers now have less chances to pick "dark side of force" (Legion, Shath'yar, Death God religions).

Secret Changelog:

- Banned "Personally Adopt Faith" decision for AI patricians, theocracies, holy orders and mercenaries.
- "Faction" government now can't imprison and revoke titles without reason.
- Refactored "Fury of the Wolf" event chain to make it less CPU heavy.
- Reworked triggers of target society missions like "Turn Undead" and "Mind Control".
- Reworked "The New Lich King" text and "Lich King" localization.
- Tauren CoAs can be used only by characters with Earth Mother, Shamanic religions, while orcish CoAs - only by Fel-tainted and Ancestral religions.
- Added dynasty names for "Demonic" cultures.
- Refactored Ashbringer event chain.
- Refactored "Restore Mana" warlock ability.
- Adapted TOG.1210 event AKA "An ambitious character with no inheritance begins to plan an adventure for a foreign title"
- Refactored spawned troops. "Invaders Strength" game rule affects spawned qiraji troops. P.S. Not "Old God building".

### CODE REVIEW

**Comment by MemeWizard** [comment]
>Ok, now the Kaldorei Empire and its vassals REALLY prefer to stay it de-jure borders.

Qiraji too

<details>

image

</details>

>Non-evil characters can always join factions against evil liege and vice versa.

This is ok?

<details>

image

</details>

>Negative fertility of some race traits is replaced by "Infertile" trait. Such long-lived races and immortal characters get it when they have too many children. Non-long-lived races get it when they reach andropause/menopause age.

Don't affect historical characters
Also, icon is ugly.

<details>

image

</details>

>Sometimes the game spawns groups of sea invaders like kvaldir, naga and murlocs to settle on your coast. (Note for testers: tell me if this happens too often).

They don't have education

<details>

image
image
image

</details>

And, for some reason, war just end without any explanation why

<details>

image
image

</details>

Maybe because they are 300 years old murlocs and die from short lifespawn

<details>

image

</details>

Kvaldir religion changes from Helya to shadowlander and cb become invalid

<details>

image
image
image

</details>

**Comment by MemeWizard** [comment]
Event desc is too long

<details>

image

</details>

>"Burn Evil Being" and "Burn Evil Beings" decisions can be now used to get reason to execute your landed vassals. AI just takes their lands via these decisions.

Wrong tooltip

<details>

image

</details>

>"Restore Mana" warlock ability is finally useable.

But it's was usable before?

**Comment by geffe1** [comment]
>Theramore is connected to mainland. Plus, now Theramore get more lands after founding.

Unsure how accurate the new lands are though, as I believe there is very few humans living in the areas which were given to Theramore with this patch. But it is correct.

I would however dispute these two provinces, but if it is correct that they own them.. then for sure they are very overrun by Murlocs and and other sea creatures. 
ck2_277

**Comment by geffe1** [comment]
>You no longer can use your Chancellor to improve diplomatic relations with Death God, Legion and Shath'yar rulers.

Very true, but you can still do it with their vassals who are evil just like them. Which I see no point in either, as they are under the Lich King's control no matter if they used to like you or not.
ck2_278

**Comment by MemeWizard** [comment]
>Very true, but you can still do it with their vassals who are evil just like them.

Probably there some non-evil barons in these provinces

**Comment by geffe1** [comment]
> Probably there some non-evil barons in these provinces

I do not think it matters, as it is towards Arthas- who is the Lich King's puppet.

**Comment by zumbak04** [comment]
> I do not think it matters, as it is towards Arthas- who is the Lich King's puppet.

No, in this case you should improve relations with non-evil barons in this county. Try to wait till Chancellor do its job.

**Comment by geffe1** [comment]
>After "Exodus of the Horde", "Founding of Theramore" event chains, landless character from your dynasty gets abandoned titles if you have one. Otherwise, your liege gets these titles.

This doesn't seem to work.. properly. Killed Jaina via the  console and got the event, after founding Theramore this happened.

ck2_304

**Comment by zumbak04** [comment]
> But it's was usable before?

Incorrect change note. Purged it. I just refactored this ability. Nothing special. Should work the same way, but better. :3

> Unsure how accurate the new lands are though, as I believe there is very few humans living in the areas which were given to Theramore with this patch. But it is correct.
> 
> I would however dispute these two provinces, but if it is correct that they own them.. then for sure they are very overrun by Murlocs and and other sea creatures.

I just want Theramore to be stronk and form its duchy as fast as possible. Also, I didn't get what two provinces you mean.

**Comment by zumbak04** [comment]
@MemeWizard @geffe1 , fixed everything you mentioned. Waiting for new reviews.

**Comment by MemeWizard** [comment]
>Gave more troops to sea invaders like kvaldir, naga and murlocs because they became a bit rare due to refactoring.

*>* Murloc have 7k army
*>* Gilneas have 8k
Result:

<details>

image


</details>

**Comment by geffe1** [comment]
Tried the Theramore thing twice now, noticed that if you are underneath a liege everything gets transferred to somebody else like it is meant to work. However, if you are independent, then you get to keep all the lands in your old territory even with living relatives, like a son.  Unsure if this is meant to be the case or not, but it feels like you should leave everything behind. Felt like sharing it either way.
ck2_307

**Comment by zumbak04** [comment]
> Tried the Theramore thing twice now, noticed that if you are underneath a liege everything gets transferred to somebody else like it is meant to work. However, if you are independent, then you get to keep all the lands in your old territory even with living relatives, like a son. Unsure if this is meant to be the case or not, but it feels like you should leave everything behind. Felt like sharing it either way.

Not sure it works in the lore. Like Thrall didn't leave Horde lands in the EK when he sailed to Kalimdor.

**Comment by zumbak04** [comment]
> _>_ Murloc have 7k army
> _>_ Gilneas have 8k
> Result:
> 
> Imo. now invasions are too strong

Randomized it a bit. Test now.

**Comment by MemeWizard** [comment]
>Randomized it a bit. Test now.

Imo, they still too strong.

<details>

image

</details>

>Theramore
Titles with elective succession will be transferred to liege, not successor. Is that ok? 

<details>

image
image

</details>

**Comment by zumbak04** [comment]
> Titles with elective succession will be transferred to liege, not successor. Is that ok?

Yes, it doesn't give titles to your heirs... or to characters that are heirs of something.

**Comment by geffe1** [comment]
>Now new rulers of Gnomeregan and Ironforge can instantly propose alliance to each other via event chain.

Noooot really....? They do it after one of their leaders die. This event doesn't appear to fire otherwise from my testing. Otherwise everything else seems ok.

**Comment by MemeWizard** [comment]
>They do it after one of their leaders die.

And they allied from the start

<details>

image

</details>

**Pull request merged**
