### PR TITLE
Evil Laws Issues

### PR DESCRIPTION
**Pull request by zumbak04**
# Changelog
- Undead Horde, Demonic Legion and Black Pact governments should never appear with Non-Dark Pact succession type (except for Barons).
- Death God, Legion and Shath'yar character should always appear with Undead Horde/Demonic Legion/Black Pact governments (except for Theocratic Barons).
- Fixed issue where Shath'yar Nomads could become Black Pact government and get game over. They can't get Black Pact now.
- Using of Revive the Black Empire decision requires to be Black Pact government.

# How to Test
Start 603 bookmark, wait for more naga clans over the world and distribute some titles and holdings (cities, tribals, castels) and take a look at their laws.

# Notes for Zuzu (for Zumbak's eyes only)
Test the game performance since `WCGOV.5000` may be CPU heavy.

### CODE REVIEW

**Comment by MemeWizard** [comment]
> Death God, Legion and Shath'yar character should always appear with Undead Horde/Demonic Legion/Black Pact governments (except for Theocracy).

Even if their liege don't have evil government?

<details>
<summary>Click to expand</summary>

image
image

</details>

> Undead Horde, Demonic Legion and Black Pact governments should never appear with Non-Dark Pact succession type.

Are you sure?

<details>
<summary>Click to expand</summary>

image
image
image

</details>

**Comment by zumbak04** [comment]
> > Death God, Legion and Shath'yar character should always appear with Undead Horde/Demonic Legion/Black Pact governments (except for Theocracy).
> 
> Even if their liege don't have evil government?

> > Undead Horde, Demonic Legion and Black Pact governments should never appear with Non-Dark Pact succession type.
> 
> Are you sure?

Forgot to mention that evil barons should have Gavelkind. In vanilla, barons can't have Elective succession. I don't know why Paradox did it, but I'm afraid it may be CPU heavy.

Evil count having Primogeniture should be fixed.

**Comment by MemeWizard** [comment]
Game crash when I try to start the game after 4ce4148

**Comment by zumbak04** [comment]
> Game crash when I try to start playing after [4ce4148](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/4ce414805afb0a35dda1da9727229968e695150f)

Fixed the crash.
Check the changelog. Added +2 fixes.

**Comment by MemeWizard** [comment]
> Undead Horde, Demonic Legion and Black Pact governments should never appear with Non-Dark Pact succession type (except for Barons).


<details>
<summary>Click to expand</summary>

image

image

image

</details>

**Comment by zumbak04** [comment]
> There was a problem, zon shouldnt have THAT kind of goverment when controlling Rezan temple

> so i decided to test again to get same result with another evil-religion in another temple

At first I thought it was a bug. Now... I think it's non-intended feature. Death God, Legion, Shath'yar Barons need Theocratic government because of vanilla bug. This bug doesn't affect counts, so there's no reason why they should be Theocrats. So, Theocratic Death God, Legion, Shath'yar Barons turning Undead Horde, Demonic Legion, Black Pact governments is fine. Death God, Legion, Shath'yar Counts holding temples is fine as well.

> > Undead Horde, Demonic Legion and Black Pact governments should never appear with Non-Dark Pact succession type (except for Barons).
> 
> Click to expand

Fixed!

**Pull request merged**
