### PR TITLE
Dynasty Shields for Evil Characters

### PR DESCRIPTION
**Pull request by MemeWizard**
#### Changelog:
- Added Dynasty Shields for Old Gods and Sargeras Worshipers. Related to #1265

#### How to test:

Test that dynasty shields looks ok in-game

<details>
<summary>All Dynasty Shields</summary>

old_gods_pattern

</details>

### CODE REVIEW

**Comment by KoiKarp** [comment]
<details>
<summary>Click to expand</summary>



</details>

**Comment by MemeWizard** [comment]
Need more info because I can't reproduce that

<details>
<summary>Click to expand</summary>

image

</details>

**Comment by KoiKarp** [comment]
nvm, it works, my mistake

**Comment by zumbak04** [comment]
Also, it's sad you decided to remove the 2 CoAs we discussed in the PMs. They're nice.

**Comment by MemeWizard** [comment]
> Some CoAs are too small

Which ones?

> others go beyond the borders

I doubt tentacle boys care about that kind of stuff, but ok

<details>
<summary>New</summary>

old_gods_pattern

</details>

> Also, it's sad you decided to remove the 2 CoAs we discussed in the PMs. They're nice.

They were too well-known and memey

**Comment by MemeWizard** [comment]
Also, I gave these symbols to sargerite characters too

**Comment by zumbak04** [comment]
> > Some CoAs are too small
> 
> Which ones?

@MemeWizard the ones that don't "touch" the borders. Though, now it's more or less fine.

> Also, I gave these symbols to sargerite characters too
Sooo, what about the Scourge? :3

**Comment by MemeWizard** [comment]
> Sooo, what about the Scourge? :3

Wanna give them to the dead boys too?

**Comment by zumbak04** [comment]
> Wanna give them to the dead boys too?

Yes, they look like Shadowlands runes.
<details>
<summary>Click to expand</summary>

image
</details>

Also, you could give it to:
- `voidfarer`
- `fire_cult`
- `neptulon_worship`
- `therazane_worship`
- `alakir_worship`
- `illidari`
- `theradras_worship`
- `shadowlander`

**Comment by MemeWizard** [comment]
@zumbak04, check it now

**Pull request merged**
