### PR TITLE
7th Small Improvements

### PR DESCRIPTION
**Pull request by zumbak04**
Changelog:

- "Build an observatory" decision is back and adapted.
- Added rule that regulate using of "Holy War" CB.
- Now all races switch portraits when they shapeshift into druid forms.
- Removed uncolonized lands.
- Jaina is now a sorcerer and located in Dalaran at the start of the RoC bookmark.
- Instead of Unholy Architecture province modifier, the game spawns buildings in provinces after conversion to Death God, Shath'yar and Legion religions.
- Dragon consorts are a thing now. They're no longer just lovers.
- Notifications of the Plague in province no longer fire in super big stack.
- Raiders no longer can corrupt the Sunwell, burn the world trees, destroy the Dark Portal and kill C'thun.
- More religions and cultures are available in Ruler Designer... even if they're not lore-friendly.
- Added blue/green/purple portrait glow depending on being traits like "Undead", "Demon", "Void Being".

### CODE REVIEW

**Comment by geffe1** [comment]
Everything appears to work fine.. except for the holy wars- in my opinion. As I do not think the elves should be allowed to holy war the humans and the other way around. I find it super weird that they would be able to do this after being on friendly terms.
ck2_16
Still need to test:
Now all races switch portraits when they shapeshift into druid forms.
"Build an observatory" decision is back and adapted.
And more of the events that colonizes Kalimdor.

**Comment by zumbak04** [comment]
> Everything appears to work fine.. except for the holy wars- in my opinion. As I do not think the elves should be allowed to holy war the humans and the other way around. I find it super weird that they would be able to do this after being on friendly terms.

It depends on the "Holy Wars" game rule. Default is you can do holy wars if you're zealous. So, this guy, you play, isn't on friendly terms with humans.

**Comment by geffe1** [comment]
Everything appears to work, even forced a northrend.. centaur.. thing.. into being a druid and became a bird! It works, but the druid events are barely working when it comes to their texts so we really need to do something about that soon.

**Comment by MemeWizard** [comment]
>"Build an observatory" decision is back and adapted.

idk if this is ok

<details>



</details>

wrong loc

<details>


ck2_4

</details>

**Comment by zumbak04** [comment]
> does not happen when you are in secret society (in this case Legion), and your Liege change to a "evil" character and you change automatic open to legion

It happens when you change religion of province, not character.

**Comment by Sielentus** [comment]
> It happens when you change religion of province, not character.

ah okay

**Comment by zumbak04** [comment]
> idk if this is ok
> 
> wrong loc

@MemeWizard, fixed!

**Pull request merged**
