### PR TITLE
8th Small Improvements

### PR DESCRIPTION
**Pull request by zumbak04**
Changelog:
- Man'ari is now demon form of draenei. Draenei and man'ari can marry.
- Warlocks, shadow priests, death knights, necromancers can now use dark artifacts like the Scepter of Sargeras, the Apocalypse and runeblades without fulfilling religious conditions.
- Now founder of Theramore can invite one non-independent ruler to sail to Kalimdor.
- "Bless earth" now gives opinion of province holder.
- Added a few mercenaries.
- Invaders like the Horde, Scourge, Legion, Black Empire no longer can use Great War CB against other Invaders, instead of it they have Kingdom Invasion.
- Now characters join faction more faster.
- Buffed faction members and tribal monarchies.
- Added "Political Faction" government. This type of government severely limits the supreme ruler, thus preserving multiculturalism within the faction.
- Now religious heads can join factions.
- Now player can recreate the Horde or the Alliance without big reason like an invasion of the Legion or the Black Empire.
- All orcish clans get event troops when the Orcish Invasion begins.
- Gave small bonuses/maluses to all religions.
- Your Court Chaplain no longer must be necromancer to "Sew Part of Body". Now learned character can do this.
- You no longer can subjugate the Horde and Alliance.
- Tribals can "Pillage Holding"... AI won't do it anyway because it cares about infrastructure.

### CODE REVIEW

**Comment by MemeWizard** [comment]
>All orcish clans get event troops when the Orcish Invasion begins.

But only the Horde warchief get ships

**Comment by MemeWizard** [comment]
>Your Court Chaplain no longer must be necromancer to "Sew Part of Body". Now learned character can do this.

>faqih

<details>

image

</details>

**Comment by zumbak04** [comment]
> But only the Horde warchief get ships

Fixed!

> faqih

Purged!

**Comment by geffe1** [comment]
>Tribals can "Pillage Holding"... AI won't do it anyway because it cares about infrastructure.

ck2_246
ck2_245
Yes, however tribal kingdoms can not! I assume this is meant to be the case, but just wanted to make sure.
>All orcish clans get event troops when the Orcish Invasion begins.

ck2_239
Yes, this is true.. and the ships are fixed, however the Horde has become even more powerful now by the looks of it. With Blackhand's troops, the horde got 30k+ without the vassals' pulling up their actual levies.

**Comment by MemeWizard** [comment]
>however tribal kingdoms can not!

WAD

**Comment by zumbak04** [comment]
> Yes, this is true.. and the ships are fixed, however the Horde has become even more powerful now by the looks of it. With Blackhand's troops, the horde got 30k+ without the vassals' pulling up their actual levies.

Nerfed. Now 30k is max.

**Pull request merged**
