### PR TITLE
Remove infection upon becoming demon, fixes #737

### LINKED ISSUE #737: Demons can get infections
**Mod Version**
081844cf

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Demons can get infections

**Steps to reproduce the issue:**
Get infection
Become demon

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

image

</details>

### PR DESCRIPTION
**Pull request by DJScias**
First ever actual code PR,  yay?

I work with C++ in my RL job but I'm not familiar with the CK2 standards and environment so I'll take every suggestion/criticism I can use.

The fix is simple really: Clear pending infections (from a wound or something before they became demon) and clear the infection trait once you become a demon. As an aside the clearing of the `pending_infection` flag is wrapped in a `hidden_effect`.

### CODE REVIEW

**Comment by zumbak04** [comment]
@DJScias , can I push one little thing here? To make sure you can't get `pending_infection` if you're demon?

**Comment by DJScias** [comment]
> @DJScias , can I push one little thing here? To make sure you can't get `pending_infection` if you're demon?

I'll look into this. This might take me a bit as I'll have to figure out how it all works but I enjoy the challenge.

**Comment by zumbak04** [comment]
> I'll look into this. This might take me a bit as I'll have to figure out how it all works but I enjoy the challenge.

It won't be a challenge, it will be a small fix from me... possibly related to the issue... Anyway, I'll do it later. Maybe not even today.

**Comment by DJScias** [comment]
@zumbak04 Pushed what I think is the "fix" that you were talking about.

I hope it looks fine, if not feel free to suggest/criticize and the like of course.

**Pull request merged**
