### PR TITLE
9th Small Improvements

### PR DESCRIPTION
**Pull request by zumbak04**
Changelog:
- Removed wealth requirements from "Great War" and "Scourge Subjugation" CBs since AI does not know how to keep money.
- Many class conditions are visible when you ask character to be your mentor and in your Intrigue Tab. Added decision to hide these decisions.
- Worshipers of Earth Mother now can be druids.
- The Kaldorei Empire and its vassals now prefer to fight for de-jure lands then expand to the Barrens.
- Added more recommended characters to the bookmarks.
- Now AI prefer to personally adopt secret faith if it's independent or its liege publicly follows this religion.
- Legion tweaks:
  - Small demonic invasions happen more often.
  - Legion army becomes stronger with each invasion.
  - Now player can see which provinces can be used to summon the Legion. Plus, these provinces are marked by "Ley Line" modifier.
  - Artifacts that can be used to summon the Legion are marked as "Powerful Magical Artifact".
  - Legion Invasion should be more common (because I made summoning conditions easier for AI).
- Abomination trait is rebalanced.
- Technocracy and Magocracy:
  - Temple holders of "Secular" religion group or "Gnomish" culture group have Technocracy as their government.
  - Temple holders of "Arcane" religion group or "Dalaranian" culture have Magocracy as their government.
- Non-aggressive religions now subjugate non-aggressive heretics instead of conquering their titles via "Holy War" CB.
- "Court Dwarf" title is back. Small humanoids and dwarves (I mean vanilla trait) can be appointed as it.
- Small humanoid and some races can be appointed as "Guardian of the Deep" if you have "Underground City" wonder with "Guardian of the Deep" upgrade.
- Evil guys now can conquer oversea provinces.
- Now AI is going to unite the Alliance under one ruler after 608 year.
- Scourge Subjugation no longer can be used against republics and theocracies.
- Now "Stop Invader" CB spawns dukes on territory of invader instead of kings if there are no possibly candidates.

Secret changelog:
- MNM.10020 no longer fires if your religion is Fel-tainted.
- Mentioned all traits in has_unpleasant_trait_trigger_tooltip.
- Reworked AI chance to pick evil options in Fel, Void and magic addiction events.
- Refactored elven magic addiction after the Sunwell destruction.
- Refactored event chain where you found a chaos well.
- Legion isn't landless anymore.
- Magocracy and Technocracy are republics.
- Changed death reasons in offmap_sacrifice and WCCOU.500 to make what happened with character more clear.
- Commented out unused CBs in the mod and tied events.
- Changed ai_check_interval to 12 if there's only_independent. Looks like something isn't right with only_independent because AI won't fire decisions with it if ai_check_interval is higher then 12.
- Refactored give_to_claimant_effect.

### CODE REVIEW

**Comment by MemeWizard** [comment]
>Artifacts that can be used to summon the Legion are marked as "Powerful Magical Artifact".

It looks really weird in character effects.

<details>

image

</details>

>Technocracy and Magocracy:
Temple holders of "Secular" religion group and "Gnomish" culture group have Technocracy as their government.
Temple holders of "Arcane" religion group and "Dalaranian" culture have Magocracy as their government.

ok

<details>

image

</details>

>Mentioned all traits in has_unpleasant_trait_trigger_tooltip.

Now society mention children traits, but children can't join society.

<details>

image

</details>

**Comment by zumbak04** [comment]
> It looks really weird in character effects.

Maybe... but at least you know that this character has such artifact. No need to look through descriptions.

> Now society mention children traits, but children can't join society.

This's vanilla scripted trigger. It's used not only in our societies.

**Comment by SlaveToUnreason** [comment]
Horde Unification screen can sometimes pops up every couple of years or so, desipte Horde being already united. In attached save it happens on 3rd November.

**Comment by SlaveToUnreason** [comment]
Horde Unification screen can sometimes pops up every couple of years or so, desipte Horde being already united. In attached save it happens on 3rd November. 

[HordeUnification.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3317101/HordeUnification.zip)

**Comment by zumbak04** [comment]
> Horde Unification screen can sometimes pop up every couple of years or so, desipte Horde being already united. In attached save it happens on 3rd November.

Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/a0695b71b64831a0ca8e3a834f1571c3770ea169.

**Comment by geffe1** [comment]
>Added more recommended characters to the bookmarks.

Change the Go'el one to this:
Warchief Go'el, son of Durutan. Was found by Aedelas Blackmoore who raised and trained him into a gladiator. After escaping Blackmoore's grasp, he fled into the wilderness of Lordaeron to find the remaining free orcs. When he found his people, he heard about the undefeated Grom Hellscream of the Warsong clan, a bond grew between the two orcs after they first met. Go'el then saught out the chieftain the Frostwolf Clan, Dek'thar. Go'el was the first shaman accepted by the spirits since Drek'Thar's generation. Go'el became Warchief Doomhammer's second-in-command and after his death during the liberation of their people from the internment camps became the warchief. Their people sailed across the seas, finding new allies and foes on their journey to Kalimdor where they established a new home for the Horde.

I read it through and it was not proper, fixed that in this version. So try this one instead, if this one doesn't work then I'll get back to prodding at it.

**Comment by geffe1** [comment]
>Worshipers of Earth Mother now can be druids.
ck2_250
Explain this then, it says I must be in the druidic religious group. I think this needs a bit of a change.. you shouldn't have to abandon your current religion as a tauren to become a druid,  as their religion is very shamanistic but also druidic at that same time.

**Comment by MemeWizard** [comment]
>Explain this then, it says I must be in the druidic religious group.

Re-read tooltip, you don't need to be in the druidic religious group.

>Maybe... but at least you know that this character has such artifact. No need to look through descriptions.

No matter how comfortable it is, it will not stop looking weird in character effects with this localization.

**Comment by geffe1** [comment]
>Re-read tooltip, you don't need to be in the druidic religious group.

Correct, I learned it by just increasing my learning.

**Comment by zumbak04** [comment]
> Change the Go'el one to this:

Done!

> No matter how comfortable it is, it will not stop looking weird in character effects with this localization.

Changed this localization.

**Pull request merged**
