### PR TITLE
Harpy Portraits and Holdings

### PR DESCRIPTION
**Pull request by mdbpr1-iscteiulpt**
Guys heres the lovely portraits made by sejtalk and the holding icons i spent agees finding
While the first one i dont think needs alot of reviewing, the second ones might have better options im just not finding.

## Changelog:
- Added new harpy portraits.
- Added harpy holding icons.

### CODE REVIEW

**Comment by mdbpr1-iscteiulpt** [comment]
Zumbak again, i had a oopsie with the file coding so ASN or whatever it was called on them :3 arigato

**Comment by BronzeBaron** [comment]
Everything seems as expected.
- Portraits look good, seemed to apply to adults/children correctly. 
- Holding images applied correctly, all three (Tribal/City/Castle) look good. Razed/fire effect from raiding look to be in a good place.

**Comment by MemeWizard** [comment]
> Holdings shall be moved to separate branch.

Closing this branch then

**Comment by MemeWizard** [comment]
No need in this branch if portraits were merged and holdings are located on separate

**Pull request closed without merging**
