### PR TITLE
9.1th Bug Сrusade

### PR DESCRIPTION
**Pull request by zumbak04**
Changelog:

- Fixed issue where public Fel-tainted members of the Shadow Council could be "Under Suspicion".
- The Troll empires are now defunct once the Empire of Zul is restored.
- Combined classes like Warrior + Warlock, Warrior + Mage no longer can become paladins.

### CODE REVIEW

**Comment by Sielentus** [comment]
Empire of Zul seems to work.   i will check the other 2 soon

**Comment by Sielentus** [comment]
Empire of Zul seems to work, 
however i saw a different problem. When for example: Zul Drak turn into a high Kingdom. Zul Gurub,  Zul aman and Zul'Farrak can not turn  into a high Kingdom even if they have they rightful occupied teretorys  is it intended? please a answer

**Comment by zumbak04** [comment]
> however i saw a different problem. When for example: Zul Drak turn into a high Kingdom. Zul Gurub, Zul aman and Zul'Farrak can not turn into a high Kingdom even if they have they rightful occupied teretorys is it intended? please a answer
Nani? Created the Zul'Drak Empire.
image
Started playing the Farraki. Created the Zul'farrak Empire.
image

**Comment by MemeWizard** [comment]
Now tooltip says that troll empire titles will be forfeit, even if they are non-existing
Also, imo. this tooltip is too long

<details>

image

</details>

**Comment by Sielentus** [comment]
> > however i saw a different problem. When for example: Zul Drak turn into a high Kingdom. Zul Gurub, Zul aman and Zul'Farrak can not turn into a high Kingdom even if they have they rightful occupied teretorys is it intended? please a answer
> > Nani? Created the Zul'Drak Empire.
> > image
> > Started playing the Farraki. Created the Zul'farrak Empire.
> > image

huh indeed, sry then i had the wrong teretorys

**Comment by zumbak04** [comment]
> Now tooltip says that troll empire titles will be forfeit, even if they are non-existing
> Also, imo. this tooltip is too long

Ok, all this is now hidden.

**Comment by geffe1** [comment]
ck2_46
ck2_44
ck2_45
And I could train to become a paladin before I added the trait, so it works.

**Pull request merged**
