### PR TITLE
Nerglish (water deities) have no sky burial

### LINKED ISSUE #1120: Sky Burial
**Your mod version is:**
Newest

**What expansions do you have installed?**
All

**Are you using any submods/mods? If so, which?**
`---`

**Please explain your issue in as much detail as possible:**
Are you sure Sky Burial should be available to murlocs?

**Steps to reproduce the issue:**
Murloc must die

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

image

</details>

### PR DESCRIPTION
**Pull request by DJScias**
## Changelog:
- Nerglish (Murlocs) don't hold a sky burial.

## Developer changelog:
- Fixes  #1120. Adds a `water_deities` religion check to `sky_burial_decision`. It basically excludes them from the `primitive_group` that has the option.

# How to test:
* Play a murloc char
* Have a relative die
* Check that the decision doesn't show up anymore

# Notes:
Basically getting my feet wet again with minor small bug fixes (or attempts to) since I've only just returned to CK2 modding after a long house move journey.

It's possible there's more religions that need to be excluded or that a different fix is requested. I'm open to all suggestions and criticism as usual.

### CODE REVIEW

**Comment by arithon** [comment]
make water burial instead?^^ wb btw

**Comment by DJScias** [comment]
> make water burial instead?^^ wb btw

Possible. If that's what Zumbak wants or anyone else. And thanks! :)

**Comment by zumbak04** [comment]
> Possible. If that's what Zumbak wants or anyone else. And thanks! :)

Can't say I want, but I don't mind.

**Comment by zumbak04** [comment]
@DJScias do you want the PR to be reviewed?

**Comment by DJScias** [comment]
Yeah, feel free to review it if you think it's necessary.

I probably won't make any changes for a water burial for now unless it's really needed because that seems like a ton of work for something minor. But you da boss and me can be "that kind of Orc".

**Comment by DJScias** [comment]
Yep, all seems in order.

Good change on making it modular with that function. 👍

**Pull request merged**
