### PR TITLE
28th Bug Crusade

### LINKED ISSUE #1295: Weird holding names
**Mod Version**
37d54aac5

**Are you using any submods/mods? If so, which?**
GoA

**Please explain your issue in as much detail as possible:**
? instead of actual symbol

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

image

</details>

### LINKED ISSUE #1326: spawn_small_scourge_troops_effect
**Your mod version is:**
295219bc0

**What expansions do you have installed?**
All major

**Are you using any submods/mods? If so, which?**
GoA

**Please explain your issue in as much detail as possible:**
spawn_small_scourge_troops_effect don't spawn troops at gamestart

**Steps to reproduce the issue:**
Start the game as the Scourge

**Upload an attachment below: .zip of your save, or screenshots:**

> [effectimplementation.cpp:15851]: Script Assert! assert: "!"Invalid province"", type: "spawn_unit", location: " file: common/scripted_effects/wc_scripted_effects.txt line: 1248"

### LINKED ISSUE #1348: Sway/Antagonize by AI on targets with religion that forbids it.
**Your mod version is:**
32e75534c28ee1c52707c0db3a1fd26590f0244f

**What expansions do you have installed?**
All

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
Eredun (demon, Fel) AI was swaying and antagonizing other Eredun (demon, Fel). Noticed it when I switched to the antagonized (victim) and I got the Rival event to popup. Switched to the aggressor, couldn't reproduce antagonize probably because she ended it with the Rival event decision, but I found out she was swaying someone as well.

CharID 2107771 is swaying 2104946 (top vassal's husband). Save & screenshot provided below.

**Steps to reproduce the issue:**
As I was switching control to playable characters, just noticed being antagonized by AI. Unable to reproduce.

**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

demon sway

</details>

Note: Antagonize target is long gone, only Sway target remains.
[Eredun sway bug.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/4366260/Eredun.sway.bug.zip)

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Fixed #1295, ? symbol in one of Hearthglen Way province holdings.
- Fixed #1326 issue, where the Scourge had no start event troops in the Reign of Chaos bookmark.
- Fixed #1348 issue where the AI ignored players' swaying/antagonizing restrictions. In 10 years, you might notice Sargerite, Death God, Shath'gral AI rulers having swaying and antagonizing targets if you switch to them.

## Script changelog (ignore if you can't read CK2 script):
- Fixed `random_independent_ruler` in `RIP.4100` not having `religion_prefer_to_send_missionaries_trigger`. It should have it since `any_independent_ruler` in the trigger has it.
- Only unreformed religions (Agamaggan, Fetishistic, etc.) can get `RIP.4100`.
- Deleted leftover destroying titles after Great War CB. It's no longer needed since Horde's leader doesn't become a landless ruler like before.

### CODE REVIEW

**Comment by zumbak04** [comment]
> Everything seems to work, although one thing had me a little confused. To clarify, Sargerite/ Death God/ Old God regions are not supposed to sway others or be able to be swayed, correct? Same applies to antagonizing. If so, everything works fine, its just that the changelog had me a little confused.

@LordSilvermane yeees? What made you confused?

**Comment by LordSilvermane** [comment]
> @LordSilvermane yeees? What made you confused?

Oh, I just wasn't sure if

> Fixed #1348 issue where the AI ignored players' swaying/antagonizing restrictions. In 10 years, you might notice Sargerite, Death God, Shath'gral AI rulers having swaying and antagonizing targets if you switch to them.

meant that they _should_ be swaying and antagonizing targets. Reading it, it sounded like you fixed the issue of them not swaying targets, and that now they were able to. Just a little unclear. Regardless, this seems to work fine then

**Comment by zumbak04** [comment]
> meant that they _should_ be swaying and antagonizing targets. Reading it, it sounded like you fixed the issue of them not swaying targets, and that now they were able to. Just a little unclear. Regardless, this seems to work fine then.

I fix it if I add dis? I wanted to explain how you might notice it right in the changelog.
> In 10 years, you might notice Sargerite, Death God, Shath'gral AI rulers having swaying and antagonizing targets if you switch to them (though they shouldn't).

**Comment by LordSilvermane** [comment]
Yeah, that works better. Thanks for clarifying it!

**Comment by zumbak04** [comment]
> No question mark either. I assume thats in Hearthglen?

@cal0497, yee, typo, fixed it. Hearthglen Way it's.

**Pull request merged**
