### PR TITLE
Necromancy: Shadowlanders

### PR DESCRIPTION
**Pull request by Velius94**
Changelog:
- Added Shadowlander religion for 'unaffiliated' undead.
- Death Knights and Necromancers should now get a prompt to select a necromantic religion after finishing their training.
- Duskwood and Deadwind Pass region have been overhauled in 603 bookmark.
  - Morbent Fel has been added as a Shadowlander Necromancer republican mayor of Raven Hill.
  - Abercrombie is now a Shadowlander follower in 603.
  - Eliza is now an undead Shadowlander in 603 + fixed dynasty.
  - Moroes is now a Shadowlander undead duke-tier ruler of Karazhan in 603.
  - Ariden has been added as an undead courtier of Medivh in 583/count-tier ruler under Moroes in 603 and has Apocalypse in his inventory in both bookmarks.
- Arcane priests now have Magocracy government instead of Theocracy.
- Rulers of Secular Religion Group now can "Invite Wise Man/Woman to Court".

### CODE REVIEW

**Comment by geffe1** [comment]
ck2_5
Everything appears to work fine, not found any bugs as of yet but I will keep looking. And the glorious bending over to the Lich King is not an option before he arrives to Azeroth! Great job on that one!

**Comment by geffe1** [comment]
ck2_8
Abercrombie can spawn in any human kingdom it appears, seen him in both Gilneas and Lordaeron now. He should still be in Duskwood at the startdate, I am certain.

**Comment by geffe1** [comment]
ck2_13
Fixed.

**Comment by geffe1** [comment]
https://user-images.githubusercontent.com/31706375/57201285-5ba81e00-6f97-11e9-8dd6-1d6cc476ad72.png
I assume the option for taking power from the Blighted lands got moved to the other branch? If so I have no more things to report. Because I have toyed around a bit more with this branch and that option is not a thing anymore.

**Comment by Velius94** [comment]
Drust were moved to another branch since I'm unable to complete all the necessary features before the release of 1.4

**Comment by MemeWizard** [comment]
>but you can't ask a Death knight to be your Mentor

#233

**Comment by MemeWizard** [comment]
Why Hakkari can't pray?

<details>

image

</details>

>you get not the option to join the Death God or the brighted Lands

you can:
remain independent
join LK (only if you have a lich_king_happened flag, and you can get lich_king_happened flag only if you start from 583 bookmark, so this is bug that you can't join LK if you play from 603 bookmark)
don't change religion

blighted lands are is different branch (#342)

**Comment by MemeWizard** [comment]
Why your character lose piety if he not abandoning his old religion?

**Comment by Sielentus** [comment]
> blighted lands are is different branch (#342)

okay, this explains why i got not this option

> join LK (only if you have a lich_king_happened flag, and you can get lich_king_happened flag only if you start from 583 bookmark, so this is bug that you can't join LK if you play from 603 bookmark)

indeed can confirm this 
583 bookmark 
ck2_8

603 bookmark:
ck2_7

**Comment by zumbak04** [comment]
> Why your character lose piety if he not abandoning his old religion?

It's a payment for your gods to forgive you for what you did?

**Comment by MemeWizard** [comment]
>It's a payment for your gods to forgive you for what you did?

And what if it's not your fault?

<details>

ck2_3
ck2_5
ck2_6
ck2_7

</details>

**Comment by zumbak04** [comment]
> And what if it's not your fault?

Who cares?

**Comment by zumbak04** [comment]
> Why Hakkari can't pray?

Now they can!

**Pull request merged**
