### PR TITLE
Book rename

### PR DESCRIPTION
**Pull request by MemeWizard**
#### Changelog:
- Renamed "Kama Sutra" into "A Steamy Romance Novel". _Yep, that's all._

### CODE REVIEW

**Comment by zumbak04** [comment]
@sejtalk could you find this model and make icon out of it?
https://www.wowhead.com/item=37467/a-steamy-romance-novel-forbidden-love

**Comment by sejtalk** [comment]
Well there are 4 models for all the parts from what i remember so maybe we could change the event to have all of them

**Comment by MemeWizard** [comment]
@sejtalk, there a lot of them, if you make multiple icons, I can add effect that give this book random pic+appropriate name
https://www.wowhead.com/search?q=A+Steamy+Romance+Novel

**Comment by MemeWizard** [comment]
@zumbak04, @sejtalk, done

**Pull request merged**
