### PR TITLE
23rd Bug Crusade

### PR DESCRIPTION
**Pull request by zumbak04**
## Developer changelog:
- Fixed issue where you could use **Write Libram**, **Enter the Emerald Dream**, **Forge Runeblade** decisions being imprisoned, incapable or away from your court.
- Replaced `trait = incapable` by `is_incapable = yes` where it makes sense.
- Fixed issue where becoming completely incapable (if you're bedridden, it's fine) didn't kick you out of plots.

### CODE REVIEW

**Comment by MemeWizard** [comment]
> Fixed issue where becoming Incapable didn't kick you out of plots.

Now if your character become temporary incapable from "bedridden" modifier from severe illness, plot will be abandoned
I don't think it is ok

**Comment by zumbak04** [comment]
> > Fixed issue where becoming Incapable didn't kick you out of plots.
> 
> Now if your character become temporary incapable from "bedridden" modifier from severe illness, plot will be abandoned
> I don't think it is ok

Lich King is temporary incapable too, last only 4 years, while you may be bedridden... like from 1 year to 10 years... of couse if you don't die.
Plus, you can't start new plots, but can continue old ones? Why you can't continue plots being Incapable then... in both cases people call you "vegetable".

**Comment by MemeWizard** [comment]
> Plus, you can't start new plots, but can continue old ones?

Yes, because you can't get in contact with conspirators. However, your accomplices don't need you to set a plot in motion.

> In both cases people call you "vegetable".

"Temporary incapable" doesn't fit the definition.

> Lich King is temporary incapable too, last only 4 years, while you may be bedridden... like from 1 year to 10 years... of couse if you don't die.

Deep sleep on the top of giant icicle and inability to do your job while lying in bed are quite different.

**Comment by zumbak04** [comment]
@MemeWizard mmmkay, you can start and stay in plots being Bedridden.

**Pull request merged**
