### PR TITLE
WCOME.100/SSI.61 Merge (WIP)

### LINKED ISSUE #552: [SUGGESTION] | Inhabitants Sacrificed modifier
**Describe your suggestion in full detail below:**

Inhabitants Sacrificed modifier should give negative modifiers to holding, just like vanilla modifiers from sacrificing province population.

### LINKED ISSUE #660: [SUGGESTION] | WCOME.100 is too spammy
**Describe your suggestion in full detail below:**

There is no fun in clicking on the same event window 1000 times in one war, it's just tedious

Maybe province modifier instead of holding modifier or reworking it into special CB, like vanilla flower war will improve situation?

### PR DESCRIPTION
**Pull request by MemeWizard**
#### Changelog:
- Merged WCOME.100 and SSI.61
- This fixes #660 
- Fixes #552

#### Dev Changelog:
- Close #1163

### CODE REVIEW

**Comment by sejtalk** [comment]
You know this was fixed long ago?

**Comment by MemeWizard** [comment]
> You know this was fixed long ago?

If it was fixed "long ago", then why this problem still exist on master branch?

**Comment by sejtalk** [comment]
Because it isnt merged into master branch yet

**Comment by MemeWizard** [comment]
> Because it isnt merged into master branch yet

So, not fixed

**Pull request closed without merging**
