### PR TITLE
Troll Portraits

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added troll portraits together with the undead and fel versions.

# How to test:
`event WCPOD.5013` to become an undead.
`event WCFEL.9950` to spam Fel Corruption and become a demon.

### CODE REVIEW

**Comment by zumbak04** [comment]
> * Troll emperor tier helmet has a bit too much bright blue glow. Can it be toned down a little? Its a little much right now, I think.

Did better. Replaced it by a helmet with an open face in 99d733027544782c95bc3fa0d9656ad9059fe161.

> * Witch doctor mask seems like it needs to be moved a bit to the left. Might just be the angle, but it doesn't seem to cover much of the chin.

Huh? It's the original mask position from the WoW. It doesn't cover the chin there.

> * Couldn't seem to change the tusks in ruler designer, despite seeing portraits with tusk variants.

Fixed in 9020b6022d50d333b65a52848ce1f31fda1d82ca.

**Review by Myrran — COMMENTED** [review]
- Hair color becomes lighter when character’s age is chosen as “old”;
- Troll subraces have different skin color;
- Undead troll portraits look fine;
- Fel corrupted troll portrait looks fine;
- Troll martial outfit looks fine.

Potential bugs:

- Mouth (tusks) selection in ruler designer goes like this: 1 -> 3 -> 5 -> 2 -> 4 instead of 1 -> 2 -> 3 -> 4 -> 5;
- Headgear – 1, 5, 6, 8, 11 are the same (no headgear);
- Background – 13 and 14, 18 and 19, 23 and 24 – are the same;
- Headgear 7 (hat) removes hairstyle;
- Zandalari children have wrong skin color (green instead of gray);
- Drakkari children have wrong color(blue instead of green);
- Blood troll children have wrong skin color (green instead of gray);
- Demon doesn’t have troll portrait.

Overall I like troll portraits and customization changes although troll masks is not my thing.

**Comment by zumbak04** [comment]
> * Mouth (tusks) selection in ruler designer goes like this: 1 -> 3 -> 5 -> 2 -> 4 instead of 1 -> 2 -> 3 -> 4 -> 5;

Weird. Sadly, I can't fix it. It's caused by tusks having 2 layers: behind and front.

> * Headgear – 1, 5, 6, 8, 11 are the same (no headgear);

Intended.

> * Background – 13 and 14, 18 and 19, 23 and 24 – are the same;

Intended.

> * Headgear 7 (hat) removes hairstyle;

> * Zandalari children have wrong skin colour (green instead of gray);

Greenish or bluish-grey is their original colour.
https://www.wowhead.com/npc=142502/zandalari-child

> * Drakkari children have wrong color(blue instead of green);

The Drakkari are ice (blue) trolls.

> * Blood troll children have wrong skin color (green instead of gray);

Intended. They should use the zandalari portraits.

> * Demon doesn’t have troll portrait.

Fixed in 0e1806903304134f320e5a4b964f17d541a4be66.

**Review by Myrran — APPROVED** [review]
Demonic troll portraits work fine.

**Pull request merged**
