### PR TITLE
Class immortality rework

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Class traits no longer make you long-lived.
- Adapted the Eternal Life events.

# Tasks:
<details>
<summary>Click to expand</summary>

- [x] Replace Philosopher's Stone with Potion of Divinity

</details>

# How to test:
Use `event RIP.21000` to start the Eternal Life event chain. I increased the success chance for testing purposes.

Try to spot out weird localization, other things and give your feedback. Don't need to finish all the outcomes, the event chain is very random.

### CODE REVIEW

**Comment by zumbak04** [comment]
> Frame looks misplaced

Fixed in a76a63deece7e1dfb515c4116c245563a82424f0.

> loc is in need of proofreading.

I'm not a big fan of fixing Paradox grammar mistakes.

**Comment by zumbak04** [comment]
> Hour of testing and I was unable to finish the Tree of Life section while testing different characters/different ranks/different levels of martial/diplomacy/stewardship etc skills. Since there's a bribery option and an attempt to convince option, what about a forceful option involving dueling to force your warriors to fall in line?

The Tree of Life is a diplomatic option thus only diplomacy matters.

> I'd also possibly suggest shortening the quest

That's a vanilla event chain, so shortening isn't an option.

> making it that embarking on the quest makes you leave court and appoint a regent.

This requires refactoring of the event chain, so I wouldn't do it.

**Comment by Kyraga** [comment]
@zumbak04 Do you plan on allowing AI to be able to start immortality event chain? Cause right now "Supernatural events" game rule is greyed out.

**Comment by zumbak04** [comment]
> @zumbak04 Do you plan on allowing AI to be able to start immortality event chain? Cause right now "Supernatural events" game rule is greyed out.

True, the options are back in fb1bc56c49f6904b88eccf6cf44169d93d4f8b29.

**Comment by TheJinxleet** [comment]
The NPC aspect seems to be working fine I'm playing a game about 100 years in and there are plenty of legendary humans chilling around usually barony tier theocracies  since they actually live long enough to get the event it is pretty rare though just looking through the few human characters that happen to have lived to around 130 some probably got it earlier but you can never tell until they reach a certain age threshold at least with humans anyone else is impossible to tell if they got it or not

**Comment by Kyraga** [comment]
Right, it seems I was unlucky. Setting event mtth to 1 month did the trick.

**Comment by zumbak04** [comment]
> Finally succeeded, questline seems solid. What's the success % chance at now? I feel like somewhere in the range of 30% would be a solid number for it.

Nah, immortality without Fel/Void/Necromantic magic is rare in Warcraft, so keeping the vanilla chances work better.

> Only advice I'd give is that, once the quest is completed, that the mystic leaves the court. Anveena, which was the name of mine, stayed and I suddenly had a 30 diplomacy character that was immortal I could easily employ and utilize.

That's a point.

**Pull request merged**
