### PR TITLE
Bug Crusade - 13th Chapter

### PR DESCRIPTION
**Pull request by DukeJeans**
Crusade against bugs, issues, and other small problems.
Changelog:
- Fixed issue where AI didn't declare scripted war against high elves after the Plague of Lordaeron.
- Now "Mark of Light" and "Mark of Elune" are cleared when you become undead, demon or void being.
- Event that turns you undead or demon no longer shows unlocalized line about changing your graphical culture. Example: undead_human.
- You no longer can "Unite Faction" during war.
- Fixed issue where Anduin and some orcs in the First War bookmark could have "Recently Fired" and "Fired from Council" opinions at the start of the game.
- Fixed issue where nomads could settle down in the Cenarion Circle de-jure kingdom.
- Fixed issue where Arcane, Draconic, Chi, Secular (religion groups) rulers couldn't get Advanced Administration law because they couldn't pick Religious Control Mandate.
- Fixed issue where unit model on Vigil Island was shifted into the water.
- Fixed issue where children with "Legendary Shaman X" trait didn't change portrait after adulthood.
- Fixed issue where troll, orc adventures still had Monarchy government after they settled down.

Secret changelog:
- can_switch_religion_character_trigger checks is_theocracy trigger, so now Theocracy rulers shouldn't be able to switch religion using many vanilla and mod ways.
- Refactored light_mark_dec and touch_of_elune_dec. United them in one decision. Reviewers, plz test it.
- Purged vanilla DLC recommended characters.
- Blocked assimilation, usurpation and claiming of some titles like the Scourge, Green Dragonflight, Cenarion Circle and many others to prevent possible bugs with them.
- Reworked conditions of titular titles. Now titles like orcish clans, troll tribes use common conditions.
- Trade Coalition title is creatable. Only republics can do this.

### CODE REVIEW

**Comment by MemeWizard** [comment]
>Issue #524 

Not fixed

<details>

image

</details>

>Purged vanilla DLC recommended characters.

Weird flex

Also:

<details>

image

</details>

>now Theocracy rulers shouldn't be able to switch religion using many vanilla and mod ways.

ok

<details>

image
image
image


</details>

>Now "Mark of Light" and "Mark of Elune" are cleared when you become undead, demon or void being.

They are cleared even if my char don't have them.

<details>

image

</details>

>Refactored light_mark_dec and touch_of_elune_dec. United them in one decision. Reviewers, plz test it.

The Holy Elune Light?

<details>

image
image

</details>

>Reworked conditions of titular titles. Now titles like orcish clans, troll tribes use common conditions.

Frostwolf clan require Alterac Valley, but what if Frostwolf clan never visited Alterac Valley?

<details>

image

</details>

>Fixed issue where troll, orc adventures still had Monarchy government after they settled down.

ok

<details>

image

</details>

>Fixed issue where nomads could settle down in the Cenarion Circle de-jure kingdom.

ok

<details>

image

</details>

**Comment by geffe1** [comment]
>Fixed issue where AI didn't declare scripted war against high elves after the Plague of Lordaeron.

Seen it happen, hence fixed!
>Now "Mark of Light" and "Mark of Elune" are cleared when you become undead, demon or void being.

Seems to be fixed, tried it as Arthas and the mark of Light was removed before it would have otherwise expired from his LK events.
>Event that turns you undead or demon no longer shows unlocalized line about changing your graphical culture. Example: undead_human.

Appears to be fixed.
>You no longer can "Unite Faction" during war.

Fixed.
>Fixed issue where Anduin and some orcs in the First War bookmark could have "Recently Fired" and "Fired from Council" opinions at the start of the game.

Fixed, couldn't find anyone having it at least.

**Comment by zumbak04** [comment]
> > Purged vanilla DLC recommended characters.
> 
> Weird flex
> 
> Also:

IIRC, these recommended  characters aren't moddabled.

> > now Theocracy rulers shouldn't be able to switch religion using many vanilla and mod ways.
> 
> ok

This way is hardcoded. Plus, it doesn't cause temple revoking because of religion change.


> > Fixed issue where troll, orc adventures still had Monarchy government after they settled down.
> 
> ok

The code isn't ideal and I don't see another non-laggy way. It tries to change government type only when first county is conquered. So, if first conquered county doesn't have castle or tribal holding, adventurer keeps Monarchy government.

**Comment by zumbak04** [comment]
> > Issue #524
> 
> Not fixed

Fixed!

> > Now "Mark of Light" and "Mark of Elune" are cleared when you become undead, demon or void being.
> 
> They are cleared even if my char don't have them.

Fixed!

> > Refactored light_mark_dec and touch_of_elune_dec. United them in one decision. Reviewers, plz test it.
> 
> The Holy Elune Light?

Fixed!

> > Reworked conditions of titular titles. Now titles like orcish clans, troll tribes use common conditions.
> 
> Frostwolf clan require Alterac Valley, but what if Frostwolf clan never visited Alterac Valley?

Fixed!

**Comment by geffe1** [comment]
>Fixed issue where Arcane, Draconic, Chi, Secular (religion groups) rulers couldn't get Advanced
Administration law because they couldn't pick Religious Control Mandate.

Fixed.
>Fixed issue where unit model on Vigil Island was shifted into the water.
Fixed.

>Fixed issue where children with "Legendary Shaman X" trait didn't change portrait after adulthood.

Fixed, tried it on a Kul'tiran human.
>Fixed issue where troll, orc adventures still had Monarchy government after they settled down

It changes into tribal monarchy- so fixed?
>Fixed issue where nomads could settle down in the Cenarion Circle de-jure kingdom.

Is that a bad thing?

**Comment by MemeWizard** [comment]
>Is that a bad thing?

Yes

<details>

image

</details>

**Comment by DukeJeans** [comment]
Merge merge?

**Comment by zumbak04** [comment]
> Merge merge?

No-no, wait for @geffe1

**Comment by DukeJeans** [comment]
> > Merge merge?
> 
> No-no, wait for @geffe1

Making sure, since his last reply was all 'Fixed's

**Pull request merged**
