### PR TITLE
Fixed #942 Crash

### LINKED ISSUE #942: Founding of Theramore CTD
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
v. 1.6.0
**What expansions do you have installed?**
All of them
**Are you using any submods/mods? If so, which?**
I was using the "GK Static Portraits"; "More Buildable Wonders"; and "Title Manager"
**Please explain your issue in as much detail as possible:**
I get a crash to desktop after the event "The Founding of Theramore" fires.
**Steps to reproduce the issue:**
Play the game? I started on the First War bookmark and played until the founding of Teramore event which always caused a CTD.
**Upload an attachment below: .zip of your save, or screenshots:**
[603_08_16.ck2.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3839767/603_08_16.ck2.zip)

Thank you for the assistance.

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Fixed #942 crash after the Theramore founding.

# How to test:
Download the attached save and try to play a month.
[CrashSave.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/4174865/CrashSave.zip)
Also, try to play on the master branch with this save, you should get a crash.

## Note:
The crash was caused by the liege of Fray usurping Fray after he/she lost all his/her titles. As a result, the Alliance refuges and the liege were usurping Fray at the same moment.

### CODE REVIEW

**Comment by zumbak04** [comment]
@LordSilvermane @Nelpok 
What are your CK2 and Windows versions?

**Comment by LordSilvermane** [comment]
@zumbak04 My Windows version is Windows 10, my CK2 version is 3.3.2

**Comment by zumbak04** [comment]
> @zumbak04 My Windows version is Windows 10, my CK2 version is 3.3.2

HMM... I may sound crazy, but I think the crash doesn't happen on Windows 10. @MemeWizard also has Windows 10 as I know.

**Comment by LordSilvermane** [comment]
Thats rather odd, but it would explain why I didn't get a crash.

**Comment by zumbak04** [comment]
Fix confirmed in #942 discussion, so let's hope the crash is gone forever.

**Pull request merged**
