### PR TITLE
Cenarion Fixes

### PR DESCRIPTION
**Pull request by sejtalk**
## Changelog: 
- You can no longer use decision to Form New Empire as Cenarion Circle title holder.
- You can no longer vassalize Cenarion Circle.
- Malfurion no longer gets crazy about getting Cenarion Hold.
- Somebody forgot to nerf two-headed trait along with ogres so im nerfing it now.

## Devoloper changelog:
- `remove_racial_traits_effect` removes `creature_old_god`, `creature_titan_keeper`, `creature_titan`, `creature_protector`, `creature_ancient_war`, `creature_ancient_lore`, `creature_ancient_wind` now.

### CODE REVIEW

**Comment by zumbak04** [comment]
> * No more Cenarion Empire.

I guess it's suppose to fix #584 issue (it's not really clear, rephrase the changelog), but it doesn't fix it. As @MemeWizard said you can restore the Empire of Zul and become Monarchy.

<details>
<summary>Click to expand</summary>

image
image

</details>

**Comment by sejtalk** [comment]
> > * No more Cenarion Empire.
> 
> I guess it's suppose to fix #584 issue (it's not clear, rephrase the changelog), but it doesn't fix it. As @MemeWizard said you can restore the Empire of Zul and become Monarchy.
> 
> Click to expand
> image
> image

yeah it's supposed to fix it as i used steps that Meme used, looks like i'll have to fix that one in later branch.

**Comment by zumbak04** [comment]
> * You can no longer use decision to Form New Empire.

Changelog is wrong, I can.

<details>
<summary>Click to expand</summary>

image

</details>

Also, if you plan to merge it, Milestone should be the next version, 1.7.0, not Soon.

**Comment by sejtalk** [comment]
> > * You can no longer use decision to Form New Empire.
> 
> Changelog is wrong, I can.
> 
> Click to expand
> image
> 
> Also, if you plan to merge it, Milestone should be the next version, 1.7.0, not Soon.

fixed

**Comment by sejtalk** [comment]
> Mmmkay, @sejtalk take a look at the [commit](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/913/commits/891a0d27fc2732f6aedffe3e7ad0a50d38688721) I made before the merge.

looked at it

**Pull request merged**
