### PR TITLE
1st Wonders

### PR DESCRIPTION
**Pull request by zumbak04**
Changelog:

- Added Karazhan wonder and made Medivh independent.
- Added Sunwell (and other its versions) as wonders.
- Added Necropolis wonder for Death God's worshipers and nerubians.
- Added "Twilight Citadel" wonder for Old Gods' worshipers.
- Added Soul Engine wonder for Legion's followers.

### CODE REVIEW

**Comment by geffe1** [comment]
All wonders work, however I do have some things to complain about.
ck2_1
This is the picture when you build a wonder, throughout the entire thing,  I would honestly prefer if it showed the actual wonder instead from the get go.

ck2_14
ck2_12
When you loot the Sunwell itself you won't get the withdrawal as the elves, however I assume you are just stealing stuff from it and not actually hurting the well itself- so it is probably alright.
ck2_11
This goes for all pre-existing wonders, we need names to show up instead of a portrait of nobody.
ck2_4
Looted this bell from pillaging Karazhan, it has no icon.. makes me sad, please fix.
And I also noticed that Karazhan doesn't give anything at lvl 1 or 2.
ck2_3
This is spammed constantly if you attempt to rebuild the Sunwell after you take it over as any other ruler, and corrupt it one way or another. I had it happen almost 10 times, but it still progresses after you click it down.
When all of the things I have listed here is done, I'd be willing to mark this as ready- as long as there is not other lovely items from the other wonders without pictures!

**Comment by MemeWizard** [comment]
>This is the picture when you build a wonder, throughout the entire thing, I would honestly prefer if it showed the actual wonder instead from the get go.

Vanilla thing

>This goes for all pre-existing wonders, we need names to show up instead of a portrait of nobody.

Vanilla thing

>Looted this bell from pillaging Karazhan, it has no icon.. makes me sad, please fix.

Vanilla thing

**Comment by MemeWizard** [comment]
>And I also noticed that Karazhan doesn't give anything at lvl 1 or 2.

Can't confirm this

<details>
<summary>Click to expand</summary>

image
image


</details>

**Comment by geffe1** [comment]
> > And I also noticed that Karazhan doesn't give anything at lvl 1 or 2.
> 
> Can't confirm this
> 
> Click to expand
It works, just doesn't show up in the big bar at the second startdate as the human female, while it does when you hoover over the IV with your cursor.

**Comment by MemeWizard** [comment]
>It works, just doesn't show up in the big bar at the second startdate as the worgen male owning the province, while it does when you hoover over the IV with your cursor.

This is because Karazhan is damaged at the second startdate
<details>
<summary>Click to expand</summary>

image
image


</details>

**Comment by MemeWizard** [comment]
Loc

<details>
<summary>Click to expand</summary>




</details>

**Comment by zumbak04** [comment]
> This is spammed constantly if you attempt to rebuild the Sunwell after you take it over as any other ruler, and corrupt it one way or another. I had it happen almost 10 times, but it still progresses after you click it down.

Fixed!

> Rename this to Naxxramas please :(

It's not Naxxramas! It's just a Necropolis located in the same place as Naxxramas :3

**Comment by zumbak04** [comment]
> Loc
LT.60001 got special localization in case you're evil guy.

**Comment by MemeWizard** [comment]
Burn? Not take? Why burning gives you money?

<details>
<summary>Click to expand</summary>

image

</details>

**Comment by MemeWizard** [comment]
No loc
<details>
<summary>Click to expand</summary>

image


</details>

**Comment by zumbak04** [comment]
> Burn? Not take? Why burning gives you money?

Changed it back to "take". Now it makes more sense.

> No loc

Fixed!

**Comment by MemeWizard** [comment]
You can disable Sunwell

<details>
<summary>Click to expand</summary>




</details>

**Comment by zumbak04** [comment]
> You can disable Sunwell

Fixed!

**Pull request merged**
