### PR TITLE
No Vanilla Music

### PR DESCRIPTION
**Pull request by zumbak04**
# Changelog:
- Vanilla songs can no longer play.

### CODE REVIEW

**Comment by MemeWizard** [comment]
🤔
<details>
<summary>Click to expand</summary>

image

</details>

**Comment by DukeJeans** [comment]
> 🤔
> 
> Click to expand
> image
> image
> image

I cannot recreate this. 😢

**Comment by zumbak04** [comment]
> I cannot recreate this.

We're too poor to recreate this. They're songs from music and content packs.

**Comment by zumbak04** [comment]
@MemeWizard , try now. I bought all music and content packs just to fix it.
:sob:

**Comment by MemeWizard** [comment]
<details>
<summary>Click to expand</summary>

image
image

</details>

>  I bought all music and content packs just to fix it.

lmao

**Pull request merged**
