### PR TITLE
Fix typo in the Plague of Lordaeron event popup

### LINKED ISSUE #745: Struck people of Northrend
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
MASTER BRANCH
**Please explain your issue in as much detail as possible:**
Struck people of Northrend, it should be "struck the people of Northrend".
**Upload screenshots of the problem localization:**
ck2_366

### PR DESCRIPTION
**Pull request by DJScias**
Hello there,

I had to make two commits, unfortunately, as the file was in `Windows-1252` encoding. The second commit can be used to see which line I actually changed.

Screenshot of the fixed event popup:
image

This PR should fix #745.

### CODE REVIEW

**Comment by zumbak04** [comment]
@DJScias , wait, Github is still crazy because of encoding.

**Comment by DJScias** [comment]
I see, how would I fix this? Or is it something that I just have to wait for on Github's end?

**Comment by zumbak04** [comment]
> I had to make two commits, unfortunately, as the file was in `Windows-1252` encoding. The second commit can be used to see which line I actually changed.

@DJScias , wait, @DJScias I don't get it, it should be in `Windows-1252` encoding.

**Comment by DJScias** [comment]
> > I had to make two commits, unfortunately, as the file was in `Windows-1252` encoding. The second commit can be used to see which line I actually changed.
> 
> @DJScias , wait I don't get it, it should be in `Windows-1252` encoding.

I was under the impression all files had to be in `UTF-8` encoding? If not I'll see if I can fix this.

**Comment by zumbak04** [comment]
> I was under the impression all files had to be in `UTF-8` encoding? If not I'll see if I can fix this.

Nope, but some files may be not broken (like events) if they use `UTF-8`.
https://ck2.paradoxwikis.com/Modding#Guidelines
https://ck2.paradoxwikis.com/Localisation#OpenOffice_Calc.2FLibreOffice_Calc

**Comment by DJScias** [comment]
There, that should have reset it back to `Windows-1252` and the `Files Changed` tab should look a lot cleaner!

**Pull request merged**
