### PR TITLE
31th Bug Crusade

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Fixed an issue where Arthas was the first owner of Frostmourne in the 605 bookmark.
- Fixed an issue where everyone was gender-equal with absolute-cognatic gender law.

## Script changelog (ignore if you can't read CK2 script):
- Fixed an issue where like_world_steppe_region_trigger was in 2 files: wc_scripted_triggers and wc_region_triggers.

### CODE REVIEW

**Comment by KoiKarp** [comment]
Ner'Zhul is the original owner of Frostmourne but is not in the history

<details>
<summary>Click to expand</summary>

https://gyazo.com/1ab562e7f2d23c8f9f86d9d1b7768512
</details>

<details>
<summary>Click to expand</summary>

https://gyazo.com/70ad206b248f7780e7257f07c51b1e02
</details>

**Comment by arithon** [comment]
What about the Windrunner sisters in the high elven army and Shandris in the night elven one?

**Comment by KoiKarp** [comment]
Ner'zhul is the original owner of frostmourne but isn't in the history 

<details>
<summary>Click to expand</summary>


</details>

<details>
<summary>Click to expand</summary>


</details>

**Comment by zumbak04** [comment]
> Ner'zhul is the original owner of frostmourne but isn't in the history

He shouldn't be. It's not possible.

> What about the Windrunner sisters in the high elven army and Shandris in the night elven one?

Everyone except the elves.

**Comment by LordSilvermane** [comment]
Never mind me. Checking again, it didn't reappear. Weird. Looks good

**Pull request merged**
