### PR TITLE
Issue #655

### PR DESCRIPTION
**Pull request by zumbak04**
Changelog:
- Changed borders in Uldum. Purged kingdom of Uldum.
- Now there's only 2 titles named Uldum: High Kingdom of Uldum and Temple of Uldum.

### CODE REVIEW

**Comment by MemeWizard** [comment]
No loc

<details>

image

</details>

**Comment by zumbak04** [comment]
> > Purged kingdom of Uldum

Fixed!

**Comment by MemeWizard** [comment]
How about give kingdom/empire title to the Sun-King? Otherwise, he now will be the Sun-Duke.

<details>

image


</details>

**Comment by zumbak04** [comment]
> How about give kingdom/empire title to the Sun-King? Otherwise, he now will be the Sun-Duke.

Done!

**Comment by zumbak04** [comment]
> > k_uldum.tga Deleted
> 
> Deleted from "_unused" folder?
> Weird flex

Because I used it.

**Pull request merged**
