### PR TITLE
Spellbreaker Subclass (WIP)

### PR DESCRIPTION
**Pull request by AzirZait**
Added a new class for elves

### CODE REVIEW

**Comment by zumbak04** [comment]
I wouldn't mind if it was one subclass trait... but a class. It's just not worth it. Overcomplicated.

**Comment by AzirZait** [comment]
Sej say.... Rename to demon hunter and rewrite..... sad.... okey i will do subclass

**Comment by AzirZait** [comment]
Push

**Comment by mdbpr-iscteiulpt** [comment]
What does this class do exactly?

**Comment by DukeJeans** [comment]
Dear @AzirZait,

This pull request has been **inactive for a month**, so I'm going to close it. If activity resumes, it's just as easy to re-open it for further development. ❤️

**Pull request closed without merging**
